
export type LanguageLevel = "A0" | "A1" | "A2" | "B1" | "B2" | "C1" | "C2";

export const ALL_LEVELS: LanguageLevel[] = ["A0", "A1", "A2", "B1", "B2", "C1", "C2"];

export type ModuleType = "vocabulary" | "grammar" | "listening" | "reading" | "writing" | "wordTest";

export const ALL_MODULE_TYPES: ModuleType[] = ["vocabulary", "grammar", "listening", "reading", "writing", "wordTest"];
export const MODULE_NAMES_RU: Record<ModuleType, string> = {
  vocabulary: "Лексика",
  grammar: "Грамматика",
  listening: "Аудирование",
  reading: "Чтение",
  writing: "Письмо",
  wordTest: "Тест по словам"
};

export interface VocabularyWord {
  id: string;
  german: string;
  russian: string;
  topic: string; // topicId
  level: LanguageLevel;
  consecutiveCorrectAnswers: number;
  lastTestedDate?: string; // ISO date string
  errorCount: number;
  exampleSentence?: string; // Optional, can be generated by AI
}

export interface ModuleProgress {
  score: number | null; // Percentage
  completed: boolean;
  lastAttemptDate?: string; // ISO date string
  attempts: number;
}

export interface TopicProgress {
  id: string; // e.g., "greetings"
  name: string; // e.g., "Приветствия"
  modules: Partial<Record<ModuleType, ModuleProgress>>;
  completed: boolean;
  custom?: boolean; // True if user-defined topic
}

export interface LevelProgress {
  topics: Record<string, TopicProgress>; // Keyed by topic ID
  completed: boolean;
}

export interface UserProfile {
  name?: string;
  preferredTopics?: string[];
}

export interface UserSettings {
  notificationsEnabled: boolean;
  lastActivityTimestamp?: number; // Unix timestamp
  darkMode?: boolean;
}

export interface GrammarWeaknessContext {
  level: LanguageLevel;
  topicId: string;
  topicName: string;
  moduleId?: ModuleType;
}

export interface GrammarWeaknessDetail {
  tag: string;
  count: number;
  lastEncounteredDate: string;
  exampleContexts: GrammarWeaknessContext[];
}

export interface UserData {
  currentLevel: LanguageLevel;
  currentTopicId?: string;
  profile: UserProfile;
  progress: Partial<Record<LanguageLevel, LevelProgress>>;
  vocabularyBank: VocabularyWord[];
  settings: UserSettings;
  customTopics: TopicProgress[];
  grammarWeaknesses?: Record<string, GrammarWeaknessDetail>;
}

// --- AI Generated Content Types (matches flows) ---

export interface AILessonVocabularyItem {
  german: string;
  russian: string;
  exampleSentence?: string;
}

// --- Grammar Exercise Types ---
export interface AIFillInTheBlanksQuestion {
  promptText: string;
  correctAnswers: string[];
  explanation?: string;
}

export interface AIFillInTheBlanksExercise {
  type: "fillInTheBlanks";
  instructions: string;
  questions: AIFillInTheBlanksQuestion[];
}

export interface AIMultipleChoiceQuestion {
  questionText: string;
  options: string[];
  correctAnswer: string;
  explanation?: string;
}

export interface AIMultipleChoiceExercise {
  type: "multipleChoice";
  instructions: string;
  questions: AIMultipleChoiceQuestion[];
}

export interface AISentenceConstructionTask {
  words: string[];
  possibleCorrectSentences: string[];
  explanation?: string;
}

export interface AISentenceConstructionExercise {
  type: "sentenceConstruction";
  instructions: string;
  tasks: AISentenceConstructionTask[];
}

export type AIGrammarExercise =
  | AIFillInTheBlanksExercise
  | AIMultipleChoiceExercise
  | AISentenceConstructionExercise;

// --- Standard Listening ---
export interface AILessonListeningExercise {
  script: string;
  questions: string[]; // Open-ended questions
}

// --- Interactive Vocabulary Exercise Types ---
export interface AIMatchingPair {
  german: string;
  russian: string;
}
export interface AIMatchingExercise {
  type: "matching";
  instructions: string;
  pairs: AIMatchingPair[];
  germanDistractors?: string[];
  russianDistractors?: string[];
}

export interface AIAudioQuizItem {
  germanPhraseToSpeak: string;
  options: string[]; // Russian translations
  correctAnswer: string; // One of the options
  explanation?: string;
}
export interface AIAudioQuizExercise {
  type: "audioQuiz";
  instructions: string;
  items: AIAudioQuizItem[];
}

// --- Common Interactive Exercise Types for Listening/Reading ---
export interface AIComprehensionMQ_Question {
  questionText: string;
  options: string[];
  correctAnswer: string;
  explanation?: string;
}
export interface AIComprehensionMultipleChoiceExercise {
  type: "comprehensionMultipleChoice";
  instructions: string;
  questions: AIComprehensionMQ_Question[];
}

export interface AITrueFalseStatement {
  statement: string;
  isTrue: boolean;
  explanation?: string;
}
export interface AITrueFalseExercise {
  type: "trueFalse";
  instructions: string;
  statements: AITrueFalseStatement[];
}

export interface AISequencingExercise {
  type: "sequencing";
  instructions: string;
  shuffledItems: string[];
  correctOrder: string[];
}

// --- Main Lesson Content Structure ---
export interface AILessonContent {
  lessonTitle: string;
  vocabulary: AILessonVocabularyItem[];
  grammarExplanation: string;

  grammarFillInTheBlanks?: AIFillInTheBlanksExercise;
  grammarMultipleChoice?: AIMultipleChoiceExercise;
  grammarSentenceConstruction?: AISentenceConstructionExercise;

  listeningExercise: AILessonListeningExercise;
  readingPassage: string;
  readingQuestions: string[];
  writingPrompt: string;

  interactiveMatchingExercise?: AIMatchingExercise;
  interactiveAudioQuizExercise?: AIAudioQuizExercise;

  interactiveListeningMCQ?: AIComprehensionMultipleChoiceExercise;
  interactiveListeningTrueFalse?: AITrueFalseExercise;
  interactiveListeningSequencing?: AISequencingExercise;

  interactiveReadingMCQ?: AIComprehensionMultipleChoiceExercise;
  interactiveReadingTrueFalse?: AITrueFalseExercise;
  interactiveReadingSequencing?: AISequencingExercise;
}

export interface WritingEvaluationDetails {
  taskAchievement?: string; // Оценка выполнения задания. ДОЛЖНО БЫТЬ НА РУССКОМ, ОЧЕНЬ КРАТКО
  coherenceAndCohesion?: string; // Оценка связности и логичности текста. ДОЛЖНО БЫТЬ НА РУССКОМ, КРАТКО
  lexicalResource?: string; // Оценка использования лексики. ДОЛЖНО БЫТЬ НА РУССКОМ, КРАТКО
  grammaticalAccuracy?: string; // Оценка грамматической правильности. ДОЛЖНО БЫТЬ НА РУССКОМ, КРАТКО
  overallFeedback: string; // Общее заключение и ключевые рекомендации. ДОЛЖНО БЫТЬ НА РУССКОМ, 1-2 ПРЕДЛОЖЕНИЯ
  suggestedImprovements?: string[]; // Конкретные предложения по улучшению. НА РУССКОМ
}

export interface ErrorExplanation {
  generalExplanation: string; // Общее объяснение типа ошибки на русском языке. Должно быть четким и по существу.
  specificExample?: string; // Конкретный пример из ответа пользователя, ВЫДЕЛЯЮЩИЙ ошибку (если применимо и если ошибка не во всем ответе).
  correctionExample?: string; // Пример исправления для ОШИБОЧНОГО ФРАГМЕНТА ответа пользователя (если применимо), а не полный правильный ответ. Полный ответ указывается в поле 'suggestedCorrection'.
  theoryReference?: string; // Краткое упоминание соответствующего грамматического правила или лексического нюанса на русском языке (если применимо, например, 'Предлог 'mit' требует Dativ').
}


export interface AIEvaluationResult {
  evaluation: string; // Краткий общий вывод на русском языке. Для письма это будет writingDetails.overallFeedback. Для других модулей – основная мысль оценки (например, "Верно!" или "Не совсем точно, есть ошибка в употреблении слова").
  isCorrect: boolean; // Whether the user response is correct or not. For writing, true if the text is generally understandable and addresses the prompt adequately for the level.
  suggestedCorrection?: string; // ПОЛНЫЙ предлагаемый правильный ответ на русском языке, если ответ пользователя был коротким и неверным, или ключевые исправления. Для письма это может быть исправленная версия текста.
  grammarErrorTags?: string[]; // Specific grammar points the user made errors on (e.g., "akkusativ_prepositions", "verb_conjugation_modal").
  writingDetails?: WritingEvaluationDetails;
  errorExplanationDetails?: ErrorExplanation;
}


export interface AIRecommendedLesson {
  topic: string;
  modules: string[];
  reasoning: string;
}

export interface DefaultTopicDefinition {
  id: string;
  name: string;
  /**
   * Optional list of vocabulary items for this topic.
   * If provided, the AI will be instructed to primarily use these words
   * for the lesson's vocabulary section, generating example sentences if needed,
   * and supplementing the list to reach 14-20 items if this list is shorter.
   * If not provided, AI generates vocabulary based on the topic name and level.
   */
  fallbackVocabulary?: AILessonVocabularyItem[];
}

// Default Topics (Considered "Mandatory Lexical Topics")
export const DEFAULT_TOPICS: Record<LanguageLevel, DefaultTopicDefinition[]> = {
  A0: [
    { id: "a0_alphabet_pronunciation", name: "Алфавит, произношение, буквы", fallbackVocabulary: [] },
    {
      id: "a0_greetings_farewells",
      name: "Приветствие и прощание",
      fallbackVocabulary: [
        { german: "Hallo", russian: "привет" },
        { german: "Tschüss", russian: "пока" },
        { german: "Guten Morgen", russian: "доброе утро" },
        { german: "Guten Tag", russian: "добрый день" },
        { german: "Guten Abend", russian: "добрый вечер" },
        { german: "Gute Nacht", russian: "спокойной ночи" },
        { german: "Wie geht's?", russian: "как дела?" },
      ],
    },
    {
      id: "a0_politeness_basics",
      name: "Простые фразы вежливости и ответы",
      fallbackVocabulary: [
        { german: "Bitte", russian: "пожалуйста" },
        { german: "Danke", russian: "спасибо" },
        { german: "ja", russian: "ПЕРЕВЕДИТЕ: ja" },
        { german: "nein", russian: "ПЕРЕВЕДИТЕ: nein" },
        { german: "Entschuldigung", russian: "ПЕРЕВЕДИТЕ: Entschuldigung" },
        { german: "Verzeihung", russian: "ПЕРЕВЕДИТЕ: Verzeihung" },
      ],
    },
    {
      id: "a0_numbers_0_100",
      name: "Числа (0–100)",
      fallbackVocabulary: [
        { german: "eins", russian: "ПЕРЕВЕДИТЕ: eins" },
        { german: "zwei", russian: "ПЕРЕВЕДИТЕ: zwei" },
        { german: "drei", russian: "ПЕРЕВЕДИТЕ: drei" },
        { german: "vier", russian: "ПЕРЕВЕДИТЕ: vier" },
        { german: "fünf", russian: "ПЕРЕВЕДИТЕ: fünf" },
        { german: "sechs", russian: "ПЕРЕВЕДИТЕ: sechs" },
        { german: "sieben", russian: "ПЕРЕВЕДИТЕ: sieben" },
        { german: "acht", russian: "ПЕРЕВЕДИТЕ: acht" },
        { german: "neun", russian: "ПЕРЕВЕДИТЕ: neun" },
        { german: "zehn", russian: "ПЕРЕВЕДИТЕ: zehn" },
      ],
    },
    {
      id: "a0_colors",
      name: "Цвета",
      fallbackVocabulary: [
        { german: "Rot", russian: "красный" },
        { german: "Blau", russian: "синий" },
        { german: "Grün", russian: "зелёный" },
        { german: "Gelb", russian: "жёлтый" },
        { german: "Schwarz", russian: "чёрный" },
        { german: "Weiß", russian: "белый" },
        { german: "Braun", russian: "коричневый" },
        { german: "Grau", russian: "серый" },
      ],
    },
    {
      id: "a0_interrogative_words",
      name: "Вопросительные слова",
      fallbackVocabulary: [
        { german: "wer", russian: "ПЕРЕВЕДИТЕ: wer" },
        { german: "was", russian: "ПЕРЕВЕДИТЕ: was" },
        { german: "wo", russian: "ПЕРЕВЕДИТЕ: wo" },
        { german: "wann", russian: "ПЕРЕВЕДИТЕ: wann" },
        { german: "warum", russian: "ПЕРЕВЕДИТЕ: warum" },
        { german: "wie", russian: "ПЕРЕВЕДИТЕ: wie" },
      ],
    },
    {
      id: "a0_personal_info",
      name: "Личные данные и люди",
      fallbackVocabulary: [
        { german: "Ich", russian: "я" },
        { german: "Du", russian: "ты" },
        { german: "Er", russian: "он" },
        { german: "Sie", russian: "она" }, // Assuming "она" for "Sie" here, can be ambiguous
        { german: "Es", russian: "оно" },
        { german: "Wir", russian: "мы" },
        { german: "Ihr", russian: "вы (множественное число)" },
        // { german: "Sie", russian: "они / Вы (вежливая форма)" }, //  "Sie" is tricky due to ambiguity. Using "она" above. AI will need to be careful.
        { german: "Name", russian: "имя" },
        { german: "Alter", russian: "возраст" },
        { german: "Adresse", russian: "адрес" },
        { german: "Telefonnummer", russian: "номер телефона" },
        { german: "Mann", russian: "ПЕРЕВЕДИТЕ: Mann" },
        { german: "Frau", russian: "ПЕРЕВЕДИТЕ: Frau" },
        { german: "Freund", russian: "ПЕРЕВЕДИТЕ: Freund" },
        { german: "Freundin", russian: "ПЕРЕВЕДИТЕ: Freundin" },
        { german: "Lehrer", russian: "ПЕРЕВЕДИТЕ: Lehrer" },
        { german: "Schüler", russian: "ПЕРЕВЕДИТЕ: Schüler" },
      ],
    },
     {
      id: "a0_family",
      name: "Семья",
      fallbackVocabulary: [
        { german: "Mutter", russian: "мать" },
        { german: "Vater", russian: "отец" },
        { german: "Eltern", russian: "родители" },
        { german: "Bruder", russian: "брат" },
        { german: "Schwester", russian: "сестра" },
        { german: "Kind", russian: "ребёнок" },
        { german: "Familie", russian: "семья" },
      ],
    },
    {
      id: "a0_home_living",
      name: "Дом и жильё",
      fallbackVocabulary: [
        { german: "Haus", russian: "дом" },
        { german: "Wohnung", russian: "квартира" },
        { german: "Zimmer", russian: "комната" },
        { german: "Küche", russian: "кухня" },
        { german: "Bad", russian: "ванная" },
        { german: "Schlafzimmer", russian: "ПЕРЕВЕДИТЕ: Schlafzimmer" },
        { german: "Bett", russian: "кровать" },
        { german: "Tisch", russian: "стол" },
        { german: "Stuhl", russian: "стул" },
        { german: "Tür", russian: "ПЕРЕВЕДИТЕ: Tür" },
        { german: "Fenster", russian: "ПЕРЕВЕДИТЕ: Fenster" },
        { german: "Auto", russian: "ПЕРЕВЕДИТЕ: Auto" },
        { german: "Buch", russian: "ПЕРЕВЕДИТЕ: Buch" },
      ],
    },
    {
      id: "a0_shopping_stores",
      name: "Покупки и магазины",
      fallbackVocabulary: [
        { german: "Supermarkt", russian: "супермаркет" },
        { german: "Bäckerei", russian: "пекарня" },
        { german: "Preis", russian: "цена" },
        { german: "Euro", russian: "евро" },
        { german: "Cent", russian: "цент" },
        { german: "Kasse", russian: "касса" },
        { german: "Einkaufen", russian: "делать покупки" },
      ],
    },
    {
      id: "a0_food_drinks",
      name: "Еда и напитки",
      fallbackVocabulary: [
        { german: "Wasser", russian: "вода" },
        { german: "Brot", russian: "хлеб" },
        { german: "Milch", russian: "молоко" },
        { german: "Käse", russian: "сыр" },
        { german: "Apfel", russian: "яблоко" },
        { german: "Banane", russian: "банан" },
        { german: "Fleisch", russian: "мясо" },
        { german: "Fisch", russian: "рыба" },
        { german: "essen", russian: "ПЕРЕВЕДИТЕ: essen"},
        { german: "trinken", russian: "ПЕРЕВЕДИТЕ: trinken"},
        { german: "Frühstück", russian: "ПЕРЕВЕДИТЕ: Frühstück" },
        { german: "Mittagessen", russian: "ПЕРЕВЕДИТЕ: Mittagessen" },
        { german: "Abendessen", russian: "ПЕРЕВЕДИТЕ: Abendessen" },
      ],
    },
    {
      id: "a0_time_calendar",
      name: "Время и календарь",
      fallbackVocabulary: [
        { german: "Uhr", russian: "часы" },
        { german: "Minute", russian: "минута" },
        { german: "Stunde", russian: "час" },
        { german: "Tag", russian: "день" },
        { german: "Nacht", russian: "ПЕРЕВЕДИТЕ: Nacht" },
        { german: "Morgen", russian: "утро" }, // Assuming "утро", not "завтра" here
        { german: "Abend", russian: "вечер" },
        { german: "Woche", russian: "неделя" },
        { german: "Monat", russian: "месяц" },
        { german: "Jahr", russian: "год" },
        { german: "Montag", russian: "понедельник" },
        { german: "Dienstag", russian: "вторник" },
        { german: "Mittwoch", russian: "среда" },
        { german: "Donnerstag", russian: "четверг" },
        { german: "Freitag", russian: "пятница" },
        { german: "Samstag", russian: "суббота" },
        { german: "Sonntag", russian: "воскресенье" },
        { german: "Zeit", russian: "ПЕРЕВЕДИТЕ: Zeit" },
        { german: "jetzt", russian: "ПЕРЕВЕДИТЕ: jetzt" },
        { german: "heute", russian: "ПЕРЕВЕДИТЕ: heute" },
        { german: "gestern", russian: "ПЕРЕВЕДИТЕ: gestern" },
        { german: "morgen", russian: "ПЕРЕВЕДИТЕ: morgen" }, // Could be "завтра"
      ],
    },
    {
      id: "a0_action_verbs",
      name: "Основные глаголы",
      fallbackVocabulary: [
        { german: "Sein", russian: "быть" }, // Note: sein/haben are infinitives
        { german: "Haben", russian: "иметь" },
        { german: "gehen", russian: "идти" }, // Lowercase for typical verbs
        { german: "kommen", russian: "приходить" },
        { german: "machen", russian: "делать" },
        { german: "sprechen", russian: "говорить" },
        { german: "lesen", russian: "читать" },
        { german: "schreiben", russian: "писать" },
        { german: "laufen", russian: "ПЕРЕВЕДИТЕ: laufen" },
        { german: "springen", russian: "ПЕРЕВЕДИТЕ: springen" },
        { german: "schlafen", russian: "ПЕРЕВЕДИТЕ: schlafen" },
        { german: "sitzen", russian: "ПЕРЕВЕДИТЕ: sitzen" },
        { german: "stehen", russian: "ПЕРЕВЕДИТЕ: stehen" },
        { german: "sehen", russian: "ПЕРЕВЕДИТЕ: sehen" },
        { german: "hören", russian: "ПЕРЕВЕДИТЕ: hören" },
        { german: "geben", russian: "ПЕРЕВЕДИТЕ: geben" },
        { german: "nehmen", russian: "ПЕРЕВЕДИТЕ: nehmen" },
        { german: "fahren", russian: "ПЕРЕВЕДИТЕ: fahren" },
        { german: "reisen", russian: "ПЕРЕВЕДИТЕ: reisen" },
        { german: "arbeiten", russian: "ПЕРЕВЕДИТЕ: arbeiten" },
        { german: "spielen", russian: "ПЕРЕВЕДИТЕ: spielen" },
        { german: "lernen", russian: "ПЕРЕВЕДИТЕ: lernen" },
        { german: "kennen", russian: "ПЕРЕВЕДИТЕ: kennen" },
        { german: "verstehen", russian: "ПЕРЕВЕДИТЕ: verstehen" },
        { german: "warten", russian: "ПЕРЕВЕДИТЕ: warten" },
        { german: "helfen", russian: "ПЕРЕВЕДИТЕ: helfen" },
        { german: "brauchen", russian: "ПЕРЕВЕДИТЕ: brauchen" },
        { german: "lieben", russian: "ПЕРЕВЕДИТЕ: lieben" },
        { german: "mögen", russian: "ПЕРЕВЕДИТЕ: mögen" },
        { german: "sagen", russian: "ПЕРЕВЕДИТЕ: sagen" },
        { german: "fragen", russian: "ПЕРЕВЕДИТЕ: fragen" },
      ],
    },
    {
      id: "a0_articles_determiners",
      name: "Артикли и определители",
      fallbackVocabulary: [
        { german: "der", russian: "ПЕРЕВЕДИТЕ: der" },
        { german: "die", russian: "ПЕРЕВЕДИТЕ: die" },
        { german: "das", russian: "ПЕРЕВЕДИТЕ: das" },
        { german: "ein", russian: "ПЕРЕВЕДИТЕ: ein" },
        { german: "eine", russian: "ПЕРЕВЕДИТЕ: eine" },
        { german: "kein", russian: "ПЕРЕВЕДИТЕ: kein" },
        { german: "keine", russian: "ПЕРЕВЕДИТЕ: keine" },
      ],
    },
    {
      id: "a0_basic_adjectives",
      name: "Простые прилагательные",
      fallbackVocabulary: [
        { german: "groß", russian: "ПЕРЕВЕДИТЕ: groß" },
        { german: "klein", russian: "ПЕРЕВЕДИТЕ: klein" },
        { german: "gut", russian: "ПЕРЕВЕДИТЕ: gut" },
        { german: "schlecht", russian: "ПЕРЕВЕДИТЕ: schlecht" },
        { german: "alt", russian: "ПЕРЕВЕДИТЕ: alt" },
        { german: "jung", russian: "ПЕРЕВЕДИТЕ: jung" },
        { german: "heiß", russian: "ПЕРЕВЕДИТЕ: heiß" },
        { german: "kalt", russian: "ПЕРЕВЕДИТЕ: kalt" },
        { german: "langsam", russian: "ПЕРЕВЕДИТЕ: langsam" },
        { german: "schnell", russian: "ПЕРЕВЕДИТЕ: schnell" },
        { german: "schön", russian: "ПЕРЕВЕДИТЕ: schön" },
        { german: "schwer", russian: "ПЕРЕВЕДИТЕ: schwer" },
        { german: "leicht", russian: "ПЕРЕВЕДИТЕ: leicht" },
        { german: "hoch", russian: "ПЕРЕВЕДИТЕ: hoch" },
        { german: "niedrig", russian: "ПЕРЕВЕДИТЕ: niedrig" },
        { german: "neu", russian: "ПЕРЕВЕДИТЕ: neu" },
        { german: "offen", russian: "ПЕРЕВЕДИТЕ: offen" },
        { german: "geschlossen", russian: "ПЕРЕВЕДИТЕ: geschlossen" },
        { german: "freundlich", russian: "ПЕРЕВЕДИТЕ: freundlich" },
        { german: "nett", russian: "ПЕРЕВЕДИТЕ: nett" },
      ],
    },
    {
      id: "a0_location_direction",
      name: "Местоположение и направления (простые)",
      fallbackVocabulary: [
        { german: "draußen", russian: "ПЕРЕВЕДИТЕ: draußen" },
        { german: "drinnen", russian: "ПЕРЕВЕДИТЕ: drinnen" },
        { german: "oben", russian: "ПЕРЕВЕДИТЕ: oben" },
        { german: "unten", russian: "ПЕРЕВЕДИТЕ: unten" },
        { german: "links", russian: "ПЕРЕВЕДИТЕ: links" },
        { german: "rechts", russian: "ПЕРЕВЕДИТЕ: rechts" },
        { german: "geradeaus", russian: "ПЕРЕВЕДИТЕ: geradeaus" },
      ],
    },
    {
      id: "a0_common_places_things",
      name: "Общие места и предметы",
      fallbackVocabulary: [
        { german: "Straße", russian: "ПЕРЕВЕДИТЕ: Straße" },
        { german: "Weg", russian: "ПЕРЕВЕДИТЕ: Weg" },
        { german: "Platz", russian: "ПЕРЕВЕДИТЕ: Platz" },
        { german: "Stadt", russian: "ПЕРЕВЕДИТЕ: Stadt" },
        { german: "Land", russian: "ПЕРЕВЕДИТЕ: Land" },
        { german: "Schule", russian: "ПЕРЕВЕДИТЕ: Schule" },
        { german: "Arbeit", russian: "ПЕРЕВЕДИТЕ: Arbeit" },
        { german: "Spiel", russian: "ПЕРЕВЕДИТЕ: Spiel" },
      ],
    },
    {
      id: "a0_simple_animals",
      name: "Животные (простые)",
      fallbackVocabulary: [
        { german: "Hund", russian: "ПЕРЕВЕДИТЕ: Hund" },
        { german: "Katze", russian: "ПЕРЕВЕДИТЕ: Katze" },
        { german: "Vogel", russian: "ПЕРЕВЕДИТЕ: Vogel" },
        // Fisch is already in food/drinks
      ],
    },
    {
      id: "a0_simple_conjunctions",
      name: "Простые союзы",
      fallbackVocabulary: [
        { german: "und", russian: "ПЕРЕВЕДИТЕ: und" },
        { german: "oder", russian: "ПЕРЕВЕДИТЕ: oder" },
        { german: "aber", russian: "ПЕРЕВЕДИТЕ: aber" },
        { german: "denn", russian: "ПЕРЕВЕДИТЕ: denn" },
        { german: "wenn", russian: "ПЕРЕВЕДИТЕ: wenn" },
      ],
    },
  ],
  A1: [
    { id: "a1_personal_data_details", name: "Личные данные", fallbackVocabulary: [] },
    { id: "a1_family_friends_description", name: "Семья и друзья", fallbackVocabulary: [] },
    { id: "a1_home_living_details", name: "Дом и жильё", fallbackVocabulary: [] },
    { id: "a1_food_drinks_order", name: "Еда и напитки", fallbackVocabulary: [] },
    { id: "a1_clothing_shopping_preferences", name: "Одежда и покупки", fallbackVocabulary: [] },
    { id: "a1_city_transport_navigation", name: "Город и транспорт", fallbackVocabulary: [] },
    { id: "a1_time_calendar_daily_routine_schedule", name: "Время и календарь", fallbackVocabulary: [] },
    { id: "a1_weather_seasons_activities", name: "Погода", fallbackVocabulary: [] }
  ],
  A2: [
    { id: "a2_daily_life_routine_planning", name: "Повседневная жизнь", fallbackVocabulary: [] },
    { id: "a2_work_professions_environment", name: "Работа и профессии", fallbackVocabulary: [] },
    { id: "a2_travel_holidays_experiences", name: "Путешествия и отдых", fallbackVocabulary: [] },
    { id: "a2_shopping_services_complaints", name: "Покупки и магазины", fallbackVocabulary: [] },
    { id: "a2_health_body_appointments", name: "Здоровье", fallbackVocabulary: [] },
    { id: "a2_character_emotions_expression", name: "Характер и эмоции", fallbackVocabulary: [] },
    { id: "a2_nature_environment_protection_basic", name: "Природа и окружающая среда", fallbackVocabulary: [] }
  ],
  B1: [
    { id: "b1_education_studies_systems", name: "Образование и учёба", fallbackVocabulary: [] },
    { id: "b1_professions_career_planning_application", name: "Профессии и карьера", fallbackVocabulary: [] },
    { id: "b1_society_interpersonal_relations_issues", name: "Общество и межличностные отношения", fallbackVocabulary: [] },
    { id: "b1_media_technology_internet_impact", name: "Медиа и технологии", fallbackVocabulary: [] },
    { id: "b1_ecology_health_lifestyle_choices", name: "Экология и здоровье", fallbackVocabulary: [] },
    { id: "b1_travel_intercultural_communication_experiences", name: "Путешествия и межкультурная коммуникация", fallbackVocabulary: [] },
    { id: "b1_events_incidents_reporting", name: "События и происшествия", fallbackVocabulary: [] }
  ],
  B2: [
    { id: "b2_politics_economics_global_systems", name: "Политика и экономика", fallbackVocabulary: [] },
    { id: "b2_science_technology_innovations_discussion", name: "Наука и техника", fallbackVocabulary: [] },
    { id: "b2_culture_art_literature_analysis", name: "Культура и искусство", fallbackVocabulary: [] },
    { id: "b2_work_career_advanced_strategies", name: "Работа и карьера", fallbackVocabulary: [] },
    { id: "b2_social_issues_discussion_solutions", name: "Социальные проблемы", fallbackVocabulary: [] }
  ],
  C1: [
    { id: "c1_philosophy_psychology_ethics_concepts", name: "Философия и психология", fallbackVocabulary: [] },
    { id: "c1_political_debates_globalization_analysis", name: "Политические дебаты", fallbackVocabulary: [] },
    { id: "c1_science_global_challenges_ai_implications", name: "Наука и глобальные вызовы", fallbackVocabulary: [] },
    { id: "c1_academic_professional_lexis_discourse", name: "Академическая и профессиональная лексика", fallbackVocabulary: [] }
  ],
  C2: [
    { id: "c2_literary_publicistic_language_nuances", name: "Литературный и публицистический язык", fallbackVocabulary: [] },
    { id: "c2_legal_scientific_style_application", name: "Юридический и научный стиль", fallbackVocabulary: [] },
    { id: "c2_formal_informal_registers_diplomacy_discourse", name: "Формальный и неформальный регистры", fallbackVocabulary: [] },
    { id: "c2_translation_interpretation_cultural_nuances_practice", name: "Перевод и интерпретация", fallbackVocabulary: [] }
  ],
};

// Mandatory Grammar Topics per Level
export const MANDATORY_GRAMMAR_TOPICS: Record<LanguageLevel, string[]> = {
    A0: [
    "Алфавит и фонетика (произношение букв, ударения)",
    "Личные местоимения (ich, du, er, sie, es, wir, ihr, sie, Sie)",
    "Глагол sein в настоящем времени (ich bin, du bist…)",
    "Глагол haben в настоящем времени",
    "Простое повествовательное предложение (SVO)",
    "Простое вопросительное предложение (Ja/Nein-Fragen)",
    "Числа (0–100)",
    "Простые артикли (der, die, das – определённые)",
    "Простая лексика: дни недели, цвета, семья, еда, время"
    ],
    A1: [
    "Существительные и артикли (определённый / неопределённый)",
    "Множественное число существительных",
    "Притяжательные местоимения (mein, dein, sein…)",
    "Указательные местоимения (dieser, diese, dieses)",
    "Вопросительные слова (wer, was, wo, wann, wie, warum…)",
    "Настоящее время (Präsens) слабых и сильных глаголов",
    "Модальные глаголы (können, müssen, wollen, dürfen, sollen, mögen)",
    "Глаголы с отделяемыми приставками (aufstehen, anrufen…)",
    "Порядок слов в утвердительных, вопросительных и отрицательных предложениях",
    "Инверсия (сначала обстоятельство, потом подлежащее)",
    "Отрицание с nicht и kein",
    "Imperativ (повелительное наклонение) — вежливый и неформальный",
    "Время в часах (Uhrzeit)",
    "Именительный (Nominativ)",
    "Винительный (Akkusativ) (Ich sehe den Mann.)",
    "Простые предлоги с Akkusativ (für, durch, ohne, um…)"
    ],
    A2: [
    "Притяжательные местоимения во всех падежах",
    "Вопросительные местоимения в других падежах (Wem? Wen?)",
    "Относительные местоимения (Relativsätze mit der/die/das)",
    "Наречия частотности и времени (oft, selten, manchmal…)",
    "Наречия порядка и места (zuerst, dann, dort…)",
    "Прошедшее время: Perfekt (Ich habe gegessen, Ich bin gegangen…)",
    "Слово порядок при использовании Perfekt",
    "Präteritum некоторых глаголов (sein, haben, modal verbs)",
    "Начало освоения пассивного залога в Perfekt (wird… gemacht)",
    "Дательный падеж (Dativ)",
    "Предлоги с Dativ (mit, nach, seit, bei, von, zu…)",
    "Предлоги с Akkusativ und Dativ (an, auf, in, über…)",
    "Временные конструкции (seit, vor, in, bis)"
    ],
    B1: [
    "Относительные предложения с разными падежами",
    "Условные предложения типа I (Wenn-Sätze Typ 1)",
    "Конъюнкции: weil, obwohl, wenn, dass, damit, während",
    "Союзы и порядок слов",
    "Причастия I и II в качестве прилагательных",
    "Präteritum регулярно и часто употребляемых глаголов",
    "Различие между Präteritum и Perfekt",
    "Пассивный залог в Präsens, Präteritum и Perfekt",
    "Futur I (ich werde arbeiten)",
    "Начало Futur II (ich werde gearbeitet haben)",
    "Специальные конструкции: Es gibt / es gab",
    "Indirekte Rede mit Konjunktiv I (начало)",
    "Verben mit Präpositionen (sich freuen auf/über, warten auf)"
    ],
    B2: [
    "Konjunktiv I в косвенной речи",
    "Konjunktiv II: нереальные условные предложения (würde + Infinitiv)",
    "Konjunktiv II с Präteritum сильных глаголов (hätte, wäre, könnte, müsste)",
    "Futur II",
    "Страдательный залог (Passiv) во всех временах, в том числе с модальными глаголами",
    "Zustandspassiv (sein + Partizip II)",
    "Vorgangspassiv (werden + Partizip II)",
    "Условные предложения всех типов (Typ 1–3)",
    "Употребление инфинитивных конструкций с zu",
    "Номинализация (der Besuch → besuchen, das Lesen → lesen)",
    "Префиксы и суффиксы образования слов",
    "Сложносочинённые и сложноподчинённые предложения с Nebensätzen",
    "Рекурсия придаточных предложений"
    ],
    C1: [
    "Продвинутое использование Konjunktiv I и II",
    "Высокая частота Passiv и Umschreibungen",
    "Различия в значении при смене порядка слов",
    "Stilistische Unterschiede: Umgangssprache vs. Schriftsprache",
    "Erweiterter Infinitiv mit zu (um zu…, ohne zu…, anstatt zu…)",
    "Partizipialkonstruktionen (z.B. Von der Polizei verfolgt, rannte er weg…)",
    "Сложные причастные обороты",
    "Nominalstil vs. Verbalstil (научный стиль)",
    "Разнообразные способы выражения причины, цели, следствия"
    ],
    C2: [
    "Метафорические и идиоматические обороты",
    "Структуры высокого уровня сложности:",
    "Инверсия ради акцента: Kaum hatte er das Haus verlassen, da…",
    "Eliptische формы (пропуски глаголов/подлежащих)",
    "Dialektные и региональные формы (опционально)",
    "Структуры со сложными глаголами и вводными конструкциями",
    "Стилистические оттенки Konjunktiv I в официальных документах",
    "Академическая лексика и синтаксис",
    "Юридические и научные формулировки",
    "Перевод и переформулировка сложных идей",
    "Все времена и залоги, включая сложные и редкие формы (например, Zustandspassiv)",
    "Все формы и случаи употребления Konjunktiv I и II, включая Ersatzformen",
    "Сложные синтаксические конструкции, периоды",
    "Употребление модальных частиц для выражения оттенков значения (doch, ja, eben, halt, wohl и т.д.)",
    "Стилистически окрашенная лексика и грамматика",
    "Особенности научного и делового стиля",
    "Фразеология и идиоматика на продвинутом уровне",
    "Различия между письменной и устной речью на высоком уровне",
    "Тонкости словообразования (суффиксы, префиксы, сложные слова)",
    "Сложные случаи предложного управления и рекций глаголов"
    ],
};

    