
export type LanguageLevel = "A0" | "A1" | "A2" | "B1" | "B2" | "C1" | "C2";

export const ALL_LEVELS: LanguageLevel[] = ["A0", "A1", "A2", "B1", "B2", "C1", "C2"];

export type ModuleType = "vocabulary" | "grammar" | "listening" | "reading" | "writing" | "wordTest";

export const ALL_MODULE_TYPES: ModuleType[] = ["vocabulary", "grammar", "listening", "reading", "writing", "wordTest"];
export const MODULE_NAMES_RU: Record<ModuleType, string> = {
  vocabulary: "Лексика",
  grammar: "Грамматика",
  listening: "Аудирование",
  reading: "Чтение",
  writing: "Письмо",
  wordTest: "Тест по словам"
};

export interface VocabularyWord {
  id: string;
  german: string;
  russian: string;
  topic: string; // topicId
  level: LanguageLevel;
  consecutiveCorrectAnswers: number;
  lastTestedDate?: string; // ISO date string
  errorCount: number;
  exampleSentence?: string; // Optional, can be generated by AI
}

export interface ModuleProgress {
  score: number | null; // Percentage
  completed: boolean;
  lastAttemptDate?: string; // ISO date string
  attempts: number;
}

export interface TopicProgress {
  id: string; // e.g., "greetings"
  name: string; // e.g., "Приветствия"
  modules: Partial<Record<ModuleType, ModuleProgress>>;
  completed: boolean;
  custom?: boolean; // True if user-defined topic
}

export interface LevelProgress {
  topics: Record<string, TopicProgress>; // Keyed by topic ID
  completed: boolean;
}

export interface UserProfile {
  name?: string;
  preferredTopics?: string[];
}

export interface UserSettings {
  notificationsEnabled: boolean;
  lastActivityTimestamp?: number; // Unix timestamp
  darkMode?: boolean;
}

export interface GrammarWeaknessContext {
  level: LanguageLevel;
  topicId: string;
  topicName: string;
  moduleId?: ModuleType;
}

export interface GrammarWeaknessDetail {
  tag: string;
  count: number;
  lastEncounteredDate: string;
  exampleContexts: GrammarWeaknessContext[];
}

export interface UserData {
  currentLevel: LanguageLevel;
  currentTopicId?: string;
  profile: UserProfile;
  progress: Partial<Record<LanguageLevel, LevelProgress>>;
  vocabularyBank: VocabularyWord[];
  settings: UserSettings;
  customTopics: TopicProgress[];
  grammarWeaknesses?: Record<string, GrammarWeaknessDetail>;
}

// --- AI Generated Content Types (matches flows) ---

export interface AILessonVocabularyItem {
  german: string;
  russian: string;
  exampleSentence?: string;
}

// --- Grammar Exercise Types ---
export interface AIFillInTheBlanksQuestion {
  promptText: string;
  correctAnswers: string[];
  explanation?: string;
}

export interface AIFillInTheBlanksExercise {
  type: "fillInTheBlanks";
  instructions: string;
  questions: AIFillInTheBlanksQuestion[];
}

export interface AIMultipleChoiceQuestion {
  questionText: string;
  options: string[];
  correctAnswer: string;
  explanation?: string;
}

export interface AIMultipleChoiceExercise {
  type: "multipleChoice";
  instructions: string;
  questions: AIMultipleChoiceQuestion[];
}

export interface AISentenceConstructionTask {
  words: string[];
  possibleCorrectSentences: string[];
  explanation?: string;
}

export interface AISentenceConstructionExercise {
  type: "sentenceConstruction";
  instructions: string;
  tasks: AISentenceConstructionTask[];
}

export type AIGrammarExercise =
  | AIFillInTheBlanksExercise
  | AIMultipleChoiceExercise
  | AISentenceConstructionExercise;

// --- Standard Listening ---
export interface AILessonListeningExercise {
  script: string;
  questions: string[]; // Open-ended questions
}

// --- Interactive Vocabulary Exercise Types ---
export interface AIMatchingPair {
  german: string;
  russian: string;
}
export interface AIMatchingExercise {
  type: "matching";
  instructions: string;
  pairs: AIMatchingPair[];
  germanDistractors?: string[];
  russianDistractors?: string[];
}

export interface AIAudioQuizItem {
  germanPhraseToSpeak: string;
  options: string[]; // Russian translations
  correctAnswer: string; // One of the options
  explanation?: string;
}
export interface AIAudioQuizExercise {
  type: "audioQuiz";
  instructions: string;
  items: AIAudioQuizItem[];
}

// --- Common Interactive Exercise Types for Listening/Reading ---
export interface AIComprehensionMQ_Question {
  questionText: string;
  options: string[];
  correctAnswer: string;
  explanation?: string;
}
export interface AIComprehensionMultipleChoiceExercise {
  type: "comprehensionMultipleChoice";
  instructions: string;
  questions: AIComprehensionMQ_Question[];
}

export interface AITrueFalseStatement {
  statement: string;
  isTrue: boolean;
  explanation?: string;
}
export interface AITrueFalseExercise {
  type: "trueFalse";
  instructions: string;
  statements: AITrueFalseStatement[];
}

export interface AISequencingExercise {
  type: "sequencing";
  instructions: string;
  shuffledItems: string[];
  correctOrder: string[];
}

// --- Main Lesson Content Structure ---
export interface AILessonContent {
  lessonTitle: string;
  vocabulary: AILessonVocabularyItem[];
  grammarExplanation: string;

  grammarFillInTheBlanks?: AIFillInTheBlanksExercise;
  grammarMultipleChoice?: AIMultipleChoiceExercise;
  grammarSentenceConstruction?: AISentenceConstructionExercise;

  listeningExercise: AILessonListeningExercise;
  readingPassage: string;
  readingQuestions: string[];
  writingPrompt: string;

  interactiveMatchingExercise?: AIMatchingExercise;
  interactiveAudioQuizExercise?: AIAudioQuizExercise;

  interactiveListeningMCQ?: AIComprehensionMultipleChoiceExercise;
  interactiveListeningTrueFalse?: AITrueFalseExercise;
  interactiveListeningSequencing?: AISequencingExercise;

  interactiveReadingMCQ?: AIComprehensionMultipleChoiceExercise;
  interactiveReadingTrueFalse?: AITrueFalseExercise;
  interactiveReadingSequencing?: AISequencingExercise;
}

export interface WritingEvaluationDetails {
  taskAchievement?: string; // Оценка выполнения задания. ДОЛЖНО БЫТЬ НА РУССКОМ, ОЧЕНЬ КРАТКО
  coherenceAndCohesion?: string; // Оценка связности и логичности текста. ДОЛЖНО БЫТЬ НА РУССКОМ, КРАТКО
  lexicalResource?: string; // Оценка использования лексики. ДОЛЖНО БЫТЬ НА РУССКОМ, КРАТКО
  grammaticalAccuracy?: string; // Оценка грамматической правильности. ДОЛЖНО БЫТЬ НА РУССКОМ, КРАТКО
  overallFeedback: string; // Общее заключение и ключевые рекомендации. ДОЛЖНО БЫТЬ НА РУССКОМ, 1-2 ПРЕДЛОЖЕНИЯ
  suggestedImprovements?: string[]; // Конкретные предложения по улучшению. НА РУССКОМ
}

export interface ErrorExplanation {
  generalExplanation: string; // Общее объяснение типа ошибки на русском языке. Должно быть четким и по существу.
  specificExample?: string; // Конкретный пример из ответа пользователя, ВЫДЕЛЯЮЩИЙ ошибку (если применимо и если ошибка не во всем ответе).
  correctionExample?: string; // Пример исправления для ОШИБОЧНОГО ФРАГМЕНТА ответа пользователя (если применимо), а не полный правильный ответ. Полный ответ указывается в поле 'suggestedCorrection'.
  theoryReference?: string; // Краткое упоминание соответствующего грамматического правила или лексического нюанса на русском языке (если применимо, например, 'Предлог 'mit' требует Dativ').
}


export interface AIEvaluationResult {
  evaluation: string; // Краткий общий вывод на русском языке. Для письма это будет writingDetails.overallFeedback. Для других модулей – основная мысль оценки (например, "Верно!" или "Не совсем точно, есть ошибка в употреблении слова").
  isCorrect: boolean; // Whether the user response is correct or not. For writing, true if the text is generally understandable and addresses the prompt adequately for the level.
  suggestedCorrection?: string; // ПОЛНЫЙ предлагаемый правильный ответ на русском языке, если ответ пользователя был коротким и неверным, или ключевые исправления. Для письма это может быть исправленная версия текста.
  grammarErrorTags?: string[]; // Specific grammar points the user made errors on (e.g., "akkusativ_prepositions", "verb_conjugation_modal").
  writingDetails?: WritingEvaluationDetails;
  errorExplanationDetails?: ErrorExplanation;
}


export interface AIRecommendedLesson {
  topic: string;
  modules: string[];
  reasoning: string;
}

export interface DefaultTopicDefinition {
  id: string;
  name: string;
  /**
   * Optional list of vocabulary items for this topic.
   * If provided, the AI will be instructed to primarily use these words
   * for the lesson's vocabulary section, generating example sentences if needed,
   * and supplementing the list to reach 14-20 items if this list is shorter.
   * If not provided, AI generates vocabulary based on the topic name and level.
   * This list will be used as the primary source of vocabulary if populated by the user.
   */
  fallbackVocabulary?: AILessonVocabularyItem[];
}

// Default Topics (Considered "Mandatory Lexical Topics")
export const DEFAULT_TOPICS: Record<LanguageLevel, DefaultTopicDefinition[]> = {
  A0: [
    { id: "a0_alphabet_pronunciation", name: "Алфавит, произношение, буквы", fallbackVocabulary: [] },
    {
      id: "a0_greetings_farewells",
      name: "Приветствие и прощание",
      fallbackVocabulary: [
        { german: "Hallo", russian: "Привет" },
        { german: "Tschüss", russian: "Пока" },
        { german: "Guten Morgen", russian: "Доброе утро" },
        { german: "Guten Tag", russian: "Добрый день" },
        { german: "Guten Abend", russian: "Добрый вечер" },
        { german: "Gute Nacht", russian: "Спокойной ночи" },
        { german: "Wie geht's?", russian: "Как дела?" },
      ],
    },
    {
      id: "a0_politeness_basics",
      name: "Простые фразы вежливости",
      fallbackVocabulary: [
        { german: "Bitte", russian: "Пожалуйста / Прошу" },
        { german: "Danke", russian: "Спасибо" },
        { german: "Entschuldigung", russian: "Извините" },
        { german: "Verzeihung", russian: "Простите (более формально)" },
        { german: "ja", russian: "Да" },
        { german: "nein", russian: "Нет" },
      ],
    },
    {
      id: "a0_numbers_0_100",
      name: "Числа (0–100)",
      fallbackVocabulary: [
        { german: "eins", russian: "Один" },
        { german: "zwei", russian: "Два" },
        { german: "drei", russian: "Три" },
        { german: "vier", russian: "Четыре" },
        { german: "fünf", russian: "Пять" },
        { german: "sechs", russian: "Шесть" },
        { german: "sieben", russian: "Семь" },
        { german: "acht", russian: "Восемь" },
        { german: "neun", russian: "Девять" },
        { german: "zehn", russian: "Десять" },
      ],
    },
    {
      id: "a0_colors",
      name: "Цвета",
      fallbackVocabulary: [
        { german: "Rot", russian: "Красный" },
        { german: "Blau", russian: "Синий" },
        { german: "Grün", russian: "Зелёный" },
        { german: "Gelb", russian: "Жёлтый" },
        { german: "Schwarz", russian: "Чёрный" },
        { german: "Weiß", russian: "Белый" },
        { german: "Braun", russian: "Коричневый" },
        { german: "Grau", russian: "Серый" },
      ],
    },
    {
      id: "a0_interrogative_words",
      name: "Вопросительные слова",
      fallbackVocabulary: [
        { german: "wer", russian: "Кто" },
        { german: "was", russian: "Что" },
        { german: "wo", russian: "Где" },
        { german: "wann", russian: "Когда" },
        { german: "warum", russian: "Почему" },
        { german: "wie", russian: "Как" },
      ],
    },
    {
      id: "a0_personal_info_people",
      name: "Личные данные и люди",
      fallbackVocabulary: [
        { german: "Name", russian: "Имя" },
        { german: "Alter", russian: "Возраст" },
        { german: "Adresse", russian: "Адрес" },
        { german: "Telefonnummer", russian: "Номер телефона" },
        { german: "Mann", russian: "Мужчина / Муж" },
        { german: "Frau", russian: "Женщина / Жена" },
        { german: "Freund", russian: "Друг" },
        { german: "Freundin", russian: "Подруга" },
        { german: "Lehrer", russian: "Учитель" },
        { german: "Schüler", russian: "Ученик" },
      ],
    },
    {
      id: "a0_family",
      name: "Семья",
      fallbackVocabulary: [
        { german: "Mutter", russian: "Мать" },
        { german: "Vater", russian: "Отец" },
        { german: "Eltern", russian: "Родители" },
        { german: "Bruder", russian: "Брат" },
        { german: "Schwester", russian: "Сестра" },
        { german: "Kind", russian: "Ребёнок" },
        { german: "Familie", russian: "Семья" },
      ],
    },
    {
      id: "a0_home_living_objects",
      name: "Дом, жильё и предметы",
      fallbackVocabulary: [
        { german: "Haus", russian: "Дом" },
        { german: "Wohnung", russian: "Квартира" },
        { german: "Zimmer", russian: "Комната" },
        { german: "Küche", russian: "Кухня" },
        { german: "Bad", russian: "Ванная" },
        { german: "Schlafzimmer", russian: "Спальня" },
        { german: "Bett", russian: "Кровать" },
        { german: "Tisch", russian: "Стол" },
        { german: "Stuhl", russian: "Стул" },
        { german: "Tür", russian: "Дверь" },
        { german: "Fenster", russian: "Окно" },
        { german: "Auto", russian: "Машина" },
        { german: "Buch", russian: "Книга" },
      ],
    },
    {
      id: "a0_shopping_stores",
      name: "Покупки и магазины",
      fallbackVocabulary: [
        { german: "Supermarkt", russian: "Супермаркет" },
        { german: "Bäckerei", russian: "Пекарня" },
        { german: "Preis", russian: "Цена" },
        { german: "Euro", russian: "Евро" },
        { german: "Cent", russian: "Цент" },
        { german: "Kasse", russian: "Касса" },
        { german: "Einkaufen", russian: "Делать покупки" },
      ],
    },
    {
      id: "a0_food_drinks",
      name: "Еда и напитки",
      fallbackVocabulary: [
        { german: "Wasser", russian: "Вода" },
        { german: "Brot", russian: "Хлеб" },
        { german: "Milch", russian: "Молоко" },
        { german: "Käse", russian: "Сыр" },
        { german: "Apfel", russian: "Яблоко" },
        { german: "Banane", russian: "Банан" },
        { german: "Fleisch", russian: "Мясо" },
        { german: "Fisch", russian: "Рыба" },
        { german: "essen", russian: "Есть (кушать)" },
        { german: "trinken", russian: "Пить" },
        { german: "Frühstück", russian: "Завтрак" },
        { german: "Mittagessen", russian: "Обед" },
        { german: "Abendessen", russian: "Ужин" },
      ],
    },
    {
      id: "a0_time_calendar_weekdays",
      name: "Время, календарь и дни недели",
      fallbackVocabulary: [
        { german: "Uhr", russian: "Часы / Час (время)" },
        { german: "Minute", russian: "Минута" },
        { german: "Stunde", russian: "Час (продолжительность)" },
        { german: "Tag", russian: "День" },
        { german: "Nacht", russian: "Ночь" },
        { german: "Morgen", russian: "Утро" },
        { german: "Abend", russian: "Вечер" },
        { german: "Woche", russian: "Неделя" },
        { german: "Monat", russian: "Месяц" },
        { german: "Jahr", russian: "Год" },
        { german: "Montag", russian: "Понедельник" },
        { german: "Dienstag", russian: "Вторник" },
        { german: "Mittwoch", russian: "Среда" },
        { german: "Donnerstag", russian: "Четверг" },
        { german: "Freitag", russian: "Пятница" },
        { german: "Samstag", russian: "Суббота" },
        { german: "Sonntag", russian: "Воскресенье" },
        { german: "Zeit", russian: "Время" },
        { german: "jetzt", russian: "Сейчас" },
        { german: "heute", russian: "Сегодня" },
        { german: "gestern", russian: "Вчера" },
        { german: "morgen", russian: "Завтра" },
      ],
    },
    {
      id: "a0_action_verbs_basic",
      name: "Основные глаголы действия",
      fallbackVocabulary: [
        { german: "Sein", russian: "Быть" }, // Глаголы обычно с маленькой, но как тема...
        { german: "Haben", russian: "Иметь" },
        { german: "Gehen", russian: "Идти" },
        { german: "Kommen", russian: "Приходить" },
        { german: "Machen", russian: "Делать" },
        { german: "Sprechen", russian: "Говорить" },
        { german: "Lesen", russian: "Читать" },
        { german: "Schreiben", russian: "Писать" },
        { german: "laufen", russian: "Бежать / Ходить (пешком)" },
        { german: "springen", russian: "Прыгать" },
        { german: "schlafen", russian: "Спать" },
        { german: "sitzen", russian: "Сидеть" },
        { german: "stehen", russian: "Стоять" },
        { german: "sehen", russian: "Видеть / Смотреть" },
        { german: "hören", russian: "Слышать / Слушать" },
        { german: "geben", russian: "Давать" },
        { german: "nehmen", russian: "Брать" },
        { german: "fahren", russian: "Ехать / Ездить" },
        { german: "reisen", russian: "Путешествовать" },
        { german: "arbeiten", russian: "Работать" },
        { german: "spielen", russian: "Играть" },
        { german: "lernen", russian: "Учить / Учиться" },
        { german: "kennen", russian: "Знать (кого-то/что-то)" },
        { german: "verstehen", russian: "Понимать" },
        { german: "warten", russian: "Ждать" },
        { german: "helfen", russian: "Помогать" },
        { german: "brauchen", russian: "Нуждаться" },
        { german: "lieben", russian: "Любить" },
        { german: "mögen", russian: "Нравиться / Любить (менее интенсивно)" },
        { german: "sagen", russian: "Говорить / Сказать" },
        { german: "fragen", russian: "Спрашивать" },
      ],
    },
    {
      id: "a0_articles_pronouns",
      name: "Артикли и местоимения",
      fallbackVocabulary: [
        { german: "ich", russian: "Я" },
        { german: "du", russian: "Ты" },
        { german: "er", russian: "Он" },
        { german: "sie", russian: "Она / Они / Вы (вежл.)" },
        { german: "es", russian: "Оно" },
        { german: "wir", russian: "Мы" },
        { german: "ihr", russian: "Вы (мн.ч.)" },
        { german: "das", russian: "Это / Определенный артикль (ср.р.)" }, // das может быть и местоимением и артиклем
        { german: "der", russian: "Определенный артикль (муж.р.)" },
        { german: "die", russian: "Определенный артикль (жен.р., мн.ч.)" },
        { german: "ein", russian: "Неопределенный артикль (муж.р., ср.р.)" },
        { german: "eine", russian: "Неопределенный артикль (жен.р.)" },
        { german: "kein", russian: "Отрицательный артикль (муж.р., ср.р.)" },
        { german: "keine", russian: "Отрицательный артикль (жен.р., мн.ч.)" },
      ],
    },
    {
      id: "a0_verb_conjugations_basic_forms",
      name: "Спряжения глаголов (базовые формы)",
      fallbackVocabulary: [
        { german: "ich bin", russian: "Я есть" },
        { german: "du bist", russian: "Ты есть" },
        { german: "er ist", russian: "Он есть" },
        { german: "sie ist", russian: "Она есть" },
        { german: "es ist", russian: "Оно есть" },
        { german: "wir sind", russian: "Мы есть" },
        { german: "ihr seid", russian: "Вы (мн.ч.) есть" },
        { german: "sie sind", russian: "Они есть / Вы (вежл.) есть" },
      ],
    },
    {
      id: "a0_basic_adjectives",
      name: "Простые прилагательные",
      fallbackVocabulary: [
        { german: "groß", russian: "Большой" },
        { german: "klein", russian: "Маленький" },
        { german: "gut", russian: "Хороший" },
        { german: "schlecht", russian: "Плохой" },
        { german: "alt", russian: "Старый" },
        { german: "jung", russian: "Молодой" },
        { german: "heiß", russian: "Горячий" },
        { german: "kalt", russian: "Холодный" },
        { german: "langsam", russian: "Медленный" },
        { german: "schnell", russian: "Быстрый" },
        { german: "schön", russian: "Красивый" },
        { german: "schwer", russian: "Тяжелый / Трудный" },
        { german: "leicht", russian: "Легкий (вес / трудность)" },
        { german: "hoch", russian: "Высокий" },
        { german: "niedrig", russian: "Низкий" },
        { german: "neu", russian: "Новый" },
        { german: "offen", russian: "Открытый" },
        { german: "geschlossen", russian: "Закрытый" },
        { german: "freundlich", russian: "Дружелюбный / Приветливый" },
        { german: "nett", russian: "Милый / Приятный" },
      ],
    },
    {
      id: "a0_location_direction_simple",
      name: "Местоположение и направления (простые)",
      fallbackVocabulary: [
        { german: "draußen", russian: "Снаружи / На улице" },
        { german: "drinnen", russian: "Внутри / В помещении" },
        { german: "oben", russian: "Наверху" },
        { german: "unten", russian: "Внизу" },
        { german: "links", russian: "Налево / Слева" },
        { german: "rechts", russian: "Направо / Справа" },
        { german: "geradeaus", russian: "Прямо" },
      ],
    },
    {
      id: "a0_common_places_things",
      name: "Общие места и предметы",
      fallbackVocabulary: [
        { german: "Straße", russian: "Улица" },
        { german: "Weg", russian: "Дорога / Путь" },
        { german: "Platz", russian: "Площадь / Место" },
        { german: "Stadt", russian: "Город" },
        { german: "Land", russian: "Страна / Деревня / Земля" },
        { german: "Schule", russian: "Школа" },
        { german: "Arbeit", russian: "Работа" },
        { german: "Spiel", russian: "Игра" },
      ],
    },
    {
      id: "a0_simple_animals",
      name: "Животные (простые)",
      fallbackVocabulary: [
        { german: "Hund", russian: "Собака" },
        { german: "Katze", russian: "Кошка" },
        { german: "Vogel", russian: "Птица" },
        // Fisch уже был в еде, но тут можно повторить для контекста животных
        { german: "Fisch", russian: "Рыба (животное)" },
      ],
    },
    {
      id: "a0_simple_conjunctions",
      name: "Простые союзы",
      fallbackVocabulary: [
        { german: "und", russian: "И" },
        { german: "oder", russian: "Или" },
        { german: "aber", russian: "Но" },
        { german: "denn", russian: "Так как / Потому что" },
        { german: "wenn", russian: "Когда / Если" },
      ],
    },
  ],
  A1: [
    { id: "a1_personal_data_details", name: "Личные данные", fallbackVocabulary: [] },
    { id: "a1_family_friends_description", name: "Семья и друзья", fallbackVocabulary: [] },
    { id: "a1_home_living_details", name: "Дом и жильё", fallbackVocabulary: [] },
    { id: "a1_food_drinks_order", name: "Еда и напитки", fallbackVocabulary: [] },
    { id: "a1_clothing_shopping_preferences", name: "Одежда и покупки", fallbackVocabulary: [] },
    { id: "a1_city_transport_navigation", name: "Город и транспорт", fallbackVocabulary: [] },
    { id: "a1_time_calendar_daily_routine_schedule", name: "Время и календарь", fallbackVocabulary: [] },
    { id: "a1_weather_seasons_activities", name: "Погода", fallbackVocabulary: [] },
    // Добавляем новые темы для A1 на основе предоставленного списка слов
    {
      id: "a1_verbs_actions_common",
      name: "Общие глаголы и действия (A1)",
      fallbackVocabulary: [
        { german: "abfahren", russian: "Отправляться, отъезжать" },
        { german: "abgeben", russian: "Сдавать, отдавать" },
        { german: "abholen", russian: "Забирать, встречать" },
        { german: "anfangen", russian: "Начинать" },
        { german: "ankommen", russian: "Прибывать, приезжать" },
        { german: "ankreuzen", russian: "Отмечать крестиком" },
        { german: "anmachen", russian: "Включать (свет, прибор)" },
        { german: "anmelden", russian: "Регистрировать, записывать" },
        { german: "anrufen", russian: "Звонить (по телефону)" },
        { german: "ansehen", russian: "Смотреть, рассматривать" },
        { german: "antworten", russian: "Отвечать" },
        { german: "arbeiten", russian: "Работать" },
        { german: "aufmachen", russian: "Открывать (дверь, окно)" },
        { german: "aufräumen", russian: "Убирать, прибираться" },
        { german: "aufstehen", russian: "Вставать, подниматься" },
        { german: "ausmachen", russian: "Выключать (свет, прибор)" },
        { german: "aussehen", russian: "Выглядеть" },
        { german: "aussteigen", russian: "Выходить (из транспорта)" },
        { german: "baden", russian: "Купаться" },
        { german: "bedeuten", russian: "Значить, означать" },
        { german: "beginnen", russian: "Начинать(ся)" },
        { german: "bekommen", russian: "Получать" },
        { german: "benutzen", russian: "Использовать, пользоваться" },
        { german: "bestellen", russian: "Заказывать" },
        { german: "besuchen", russian: "Посещать, навещать" },
        { german: "bezahlen", russian: "Платить, оплачивать" },
        { german: "bleiben", russian: "Оставаться" },
        { german: "brauchen", russian: "Нуждаться, требоваться" },
        { german: "bringen", russian: "Приносить, привозить" },
        { german: "einkaufen", russian: "Делать покупки" },
        { german: "einladen", russian: "Приглашать" },
        { german: "einsteigen", russian: "Входить (в транспорт)" },
        { german: "erfahren", russian: "Узнавать (информацию)" }, // одно из значений
        { german: "erfinden", russian: "Изобретать, выдумывать" },
        { german: "ergänzen", russian: "Дополнять" },
        { german: "erhalten", russian: "Получать (формально)" },
        { german: "erklären", russian: "Объяснять" },
        { german: "erlauben", russian: "Разрешать" },
        { german: "erleben", russian: "Переживать, испытывать" },
        { german: "eröffnen", russian: "Открывать (счет, магазин)" },
        { german: "erschrecken", russian: "Пугать(ся)" },
        { german: "erziehen", russian: "Воспитывать" },
        { german: "essen", russian: "Есть, кушать" },
        { german: "fallen", russian: "Падать" },
        { german: "fernsehen", russian: "Смотреть телевизор" }, // Составной глагол, часто как fernsehen
        { german: "finden", russian: "Находить" },
        { german: "fliegen", russian: "Летать" },
        { german: "fragen", russian: "Спрашивать" },
        { german: "frühstücken", russian: "Завтракать" },
        { german: "gefallen", russian: "Нравиться" },
        { german: "gehen", russian: "Идти, ходить" },
        { german: "halten", russian: "Держать, останавливаться" },
        { german: "heißen", russian: "Называться, зваться" }, // heißt - форма
        { german: "hören", russian: "Слышать, слушать" },
        { german: "kaufen", russian: "Покупать" },
        { german: "kennen", russian: "Знать (быть знакомым)" },
        { german: "kennenlernen", russian: "Знакомиться" },
        { german: "können", russian: "Мочь, уметь" },
        { german: "kochen", russian: "Готовить (еду)" }, // Кох - повар, kochen - готовить
        { german: "kurz", russian: "Короткий / Коротко" }, // может быть и прил. и нареч.
        { german: "lachen", russian: "Смеяться" },
        { german: "lassen", russian: "Позволять, оставлять, велеть" },
        { german: "laufen", russian: "Бегать, ходить" },
        { german: "leben", russian: "Жить" },
        { german: "lesen", russian: "Читать" },
        { german: "lieben", russian: "Любить" }, // lieb - милый
        { german: "liegen", russian: "Лежать" },
        { german: "machen", russian: "Делать" },
        { german: "mögen", russian: "Любить, нравиться (хотеть)" },
        { german: "müssen", russian: "Быть должным" },
        { german: "nehmen", russian: "Брать" },
        { german: "öffnen", russian: "Открывать" },
        { german: "passen", russian: "Подходить, быть впору" },
        { german: "pilgern", russian: "Совершать паломничество" }, // довольно специфично для A1
        { german: "posten", russian: "Публиковать (в соцсетях)" },
        { german: "probieren", russian: "Пробовать, примерять" },
        { german: "putzen", russian: "Чистить, убирать" },
        { german: "raten", russian: "Советовать, угадывать" },
        { german: "reisen", russian: "Путешествовать" },
        { german: "rufen", russian: "Звать, кричать" },
        { german: "sagen", russian: "Говорить, сказать" },
        { german: "schlafen", russian: "Спать" },
        { german: "schließen", russian: "Закрывать" },
        { german: "schreiben", russian: "Писать" },
        { german: "schwimmen", russian: "Плавать" },
        { german: "sehen", russian: "Видеть, смотреть" },
        { german: "sein", russian: "Быть" },
        { german: "senden", russian: "Отправлять, передавать (по радио/ТВ)" },
        { german: "setzen", russian: "Сажать, ставить" }, // sich setzen - садиться
        { german: "singen", russian: "Петь" },
        { german: "sitzen", russian: "Сидеть" },
        { german: "sollen", russian: "Быть должным (по чьему-л. указанию)" },
        { german: "sparen", russian: "Экономить, копить" },
        { german: "spielen", russian: "Играть" },
        { german: "sprechen", russian: "Говорить, разговаривать" },
        { german: "springen", russian: "Прыгать" },
        { german: "stehen", russian: "Стоять" },
        { german: "steigen", russian: "Подниматься, садиться (в транспорт)" }, // einsteigen, aussteigen
        { german: "stellen", russian: "Ставить" },
        { german: "studieren", russian: "Учиться (в вузе), изучать" },
        { german: "suchen", russian: "Искать" },
        { german: "tanzen", russian: "Танцевать" },
        { german: "telefonieren", russian: "Говорить по телефону" },
        { german: "testen", russian: "Тестировать, проверять" },
        { german: "tun", russian: "Делать, поступать" },
        { german: "übernachten", russian: "Ночевать, переночевать" },
        { german: "überprüfen", russian: "Проверять, контролировать" },
        { german: "umziehen", russian: "Переезжать" },
        { german: "verstehen", russian: "Понимать" },
        { german: "vorstellen", russian: "Представлять(ся)" },
        { german: "warten", russian: "Ждать" },
        { german: "wiederholen", russian: "Повторять" },
        { german: "wiedersehen", russian: "Увидеться снова" },
        { german: "wohnen", russian: "Жить, проживать" },
        { german: "wollen", russian: "Хотеть" },
        { german: "wünschen", russian: "Желать" },
        { german: "zahlen", russian: "Платить" },
        { german: "zeigen", russian: "Показывать" },
        { german: "ziehen", russian: "Тянуть, переезжать" }, // umziehen, anziehen
      ]
    },
    {
      id: "a1_adjectives_adverbs_common",
      name: "Общие прилагательные и наречия (A1)",
      fallbackVocabulary: [
        { german: "alle", russian: "Все" },
        { german: "allein", russian: "Один, в одиночестве" },
        { german: "alt", russian: "Старый" },
        { german: "arm", russian: "Бедный" },
        { german: "automatisch", russian: "Автоматический" },
        { german: "besonders", russian: "Особенно, особенный" },
        { german: "billig", russian: "Дешёвый" },
        { german: "böse", russian: "Злой, сердитый" },
        { german: "breit", russian: "Широкий" },
        { german: "dick", russian: "Толстый, густой" },
        { german: "einfach", russian: "Простой, просто" },
        { german: "einverstanden", russian: "Согласен" },
        { german: "endlich", russian: "Наконец" },
        { german: "erst", russian: "Только, сначала" },
        { german: "erster", russian: "Первый" },
        { german: "fertig", russian: "Готовый" },
        { german: "frei", russian: "Свободный" },
        { german: "frisch", russian: "Свежий" },
        { german: "früh", russian: "Ранний, рано" },
        { german: "gelb", russian: "Жёлтый" },
        { german: "gern", russian: "Охотно" }, // gerne
        { german: "gestern", russian: "Вчера" },
        { german: "glücklich", russian: "Счастливый" },
        { german: "groß", russian: "Большой" },
        { german: "grün", russian: "Зелёный" },
        { german: "gut", russian: "Хороший, хорошо" },
        { german: "heiß", russian: "Горячий, жарко" },
        { german: "heute", russian: "Сегодня" },
        { german: "hier", russian: "Здесь, тут" },
        { german: "hilfreich", russian: "Полезный, услужливый" },
        { german: "immer", russian: "Всегда" },
        { german: "interessant", russian: "Интересный" },
        { german: "jeden", russian: "Каждый (Akk, m)" }, // jedes (n)
        { german: "jetzt", russian: "Сейчас, теперь" },
        { german: "kaputt", russian: "Сломанный, разбитый" },
        { german: "kurz", russian: "Короткий" }, // также как глагол
        { german: "langsam", russian: "Медленный" }, // было в А0
        { german: "letzter", russian: "Последний" },
        { german: "lieb", russian: "Милый, дорогой" },
        { german: "männlich", russian: "Мужской, мужественный" },
        { german: "möglich", russian: "Возможный" },
        { german: "morgen", russian: "Завтра" },
        { german: "neunzehn", russian: "Девятнадцать" }, // Числительное
        { german: "noch", russian: "Ещё" },
        { german: "nur", russian: "Только, лишь" },
        { german: "oft", russian: "Часто" },
        { german: "perfekt", russian: "Идеальный, совершенный" },
        { german: "praktisch", russian: "Практичный" },
        { german: "salzig", russian: "Солёный" },
        { german: "schlecht", russian: "Плохой, плохо" },
        { german: "schon", russian: "Уже" },
        { german: "selbst", russian: "Сам, самостоятельно" },
        { german: "sonnig", russian: "Солнечный" },
        { german: "spät", russian: "Поздний, поздно" },
        { german: "stark", russian: "Сильный" },
        { german: "süß", russian: "Сладкий, милый" },
        { german: "toll", russian: "Отличный, классный" },
        { german: "übermorgen", russian: "Послезавтра" },
        { german: "viel", russian: "Много" },
        { german: "vielleicht", russian: "Возможно, может быть" },
        { german: "wichtig", russian: "Важный" },
        { german: "wieder", russian: "Снова, опять" },
        { german: "wunderbar", russian: "Замечательный, чудесный" },
        { german: "zurück", russian: "Назад, обратно" },
      ]
    },
    {
      id: "a1_prepositions_conjunctions_particles",
      name: "Предлоги, союзы, частицы (A1)",
      fallbackVocabulary: [
        { german: "aber", russian: "Но, однако" },
        { german: "als", russian: "Когда (в прошлом, однократно); чем (сравнение)" },
        { german: "also", russian: "Итак, значит, следовательно" },
        { german: "auch", russian: "Также, тоже" },
        { german: "auf", russian: "На (горизонтальной поверхности); в, к (направл.)" },
        { german: "aus", russian: "Из, от (происхождение, материал)" },
        { german: "bei", russian: "У, при, около (местоположение)" },
        { german: "dann", russian: "Затем, потом, тогда" },
        { german: "ein", russian: "Один (числит.); неопред. артикль" }, // eine, einer
        { german: "er", russian: "Он" }, // личное местоимение
        { german: "es", russian: "Оно, это" }, // личное местоимение
        { german: "für", russian: "Для, за" }, // Предлог с Akkusativ
        { german: "ja", russian: "Да" },
        { german: "kein", russian: "Никакой (отриц. артикль)" },
        { german: "mal", russian: "Раз (умножение); разок (частица)" },
        { german: "man", russian: "Неопределенно-личное местоимение (кто-то, люди)" },
        { german: "mit", russian: "С, вместе с" }, // Предлог с Dativ
        { german: "nach", russian: "После; в (направление в города/страны); по" }, // Предлог с Dativ
        { german: "nein", russian: "Нет" },
        { german: "nicht", russian: "Не (отрицание)" },
        { german: "ob", russian: "Ли (косвенный вопрос)" },
        { german: "oder", russian: "Или" },
        { german: "ohne", russian: "Без" }, // Предлог с Akkusativ
        { german: "pro", russian: "За, на (единицу времени/количества)" },
        { german: "seit", russian: "С (какого-то времени, продолжается)" }, // Предлог с Dativ
        { german: "sich", russian: "Себя, себе (возвратное местоимение)" },
        { german: "sie", russian: "Она; они; Вы (вежливая форма)" }, // личное местоимение
        { german: "sondern", russian: "А, но (после отрицания)" },
        { german: "über", russian: "Над, через; о (тема)" }, // Предлог с Akkusativ/Dativ
        { german: "um", russian: "Вокруг, в (о времени)" }, // Предлог с Akkusativ
        { german: "und", russian: "И" },
        { german: "unser", russian: "Наш" }, // Притяжательное местоимение
        { german: "unter", russian: "Под; среди" }, // Предлог с Akkusativ/Dativ
        { german: "vielmal", russian: "Много раз" }, // обычно "viele Male" или "oft"
        { german: "vor", russian: "Перед; до (о времени)" }, // Предлог с Akkusativ/Dativ
        { german: "vorbei", russian: "Мимо, прошло" },
        { german: "was", russian: "Что" }, // Вопросительное местоимение
        { german: "während", russian: "Во время, в то время как" }, // Предлог с Genitiv или союз
        { german: "wir", russian: "Мы" }, // личное местоимение
        { german: "wird", russian: "Становится (форма от werden)" },
        { german: "worden", russian: "Стал (Partizip II от werden, в пассиве)" },
        { german: "zu", russian: "К, на, для (направление, цель)" }, // Предлог с Dativ
        { german: "zum Beispiel", russian: "Например" },
        { german: "zwischen", russian: "Между" }, // Предлог с Akkusativ/Dativ
      ]
    },
    {
      id: "a1_nouns_various",
      name: "Различные существительные (A1)",
      fallbackVocabulary: [
        { german: "Abfahrt", russian: "Отправление, отъезд" },
        { german: "Abteilung", russian: "Отдел, отделение" },
        { german: "Abend", russian: "Вечер" },
        { german: "Alter", russian: "Возраст" },
        { german: "Angebot", russian: "Предложение (товара, услуги)" },
        { german: "Anfang", russian: "Начало" },
        { german: "Angst", russian: "Страх" },
        { german: "Ankunft", russian: "Прибытие, приезд" },
        { german: "Anmeldung", russian: "Регистрация, заявление" },
        { german: "Anruf", russian: "Звонок (телефонный)" },
        { german: "Anrufbeantworter", russian: "Автоответчик" },
        { german: "Ansage", russian: "Объявление (по громкоговорителю)" },
        { german: "Antwort", russian: "Ответ" },
        { german: "Anzeige", russian: "Объявление (в газете), заявление (в полицию)" },
        { german: "Apfel", russian: "Яблоко" },
        { german: "Apparat", russian: "Аппарат, прибор" },
        { german: "Arbeit", russian: "Работа" },
        { german: "Arbeitsplatz", russian: "Рабочее место" },
        { german: "Arm", russian: "Рука (от плеча до кисти)" },
        { german: "Artikel", russian: "Статья; артикль (грам.)" },
        { german: "August", russian: "Август" },
        { german: "Ausgang", russian: "Выход" },
        { german: "Auskunft", russian: "Информация, справка" },
        { german: "Ausland", russian: "Заграница" },
        { german: "Ausländer", russian: "Иностранец" },
        { german: "Ausländerin", russian: "Иностранка" },
        { german: "Aussage", russian: "Высказывание, показание" },
        { german: "Ausweis", russian: "Удостоверение личности" },
        { german: "Auto", russian: "Автомобиль" },
        { german: "Automat", russian: "Автомат (торговый, игровой)" },
        { german: "Bäcker", russian: "Пекарь" },
        { german: "Bad", russian: "Ванная комната; ванна; курорт" },
        { german: "Bahn", russian: "Железная дорога; поезд" },
        { german: "Bahnhof", russian: "Вокзал" },
        { german: "Bahnsteig", russian: "Платформа (на вокзале)" },
        { german: "Ball", russian: "Мяч; бал (танцевальный вечер)" },
        { german: "Bauch", russian: "Живот" },
        { german: "Baum", russian: "Дерево" },
        { german: "Beamte", russian: "Чиновник, госслужащий" }, // Der Beamte
        { german: "Bedeutung", russian: "Значение, смысл" },
        { german: "Bein", russian: "Нога (от бедра до ступни)" },
        { german: "Beispiel", russian: "Пример" },
        { german: "Beruf", russian: "Профессия" },
        { german: "Bescheid", russian: "Уведомление, ответ, решение" },
        { german: "Bett", russian: "Кровать" },
        { german: "Bild", russian: "Картина, изображение, фотография" },
        { german: "Bleistift", russian: "Карандаш" },
        { german: "Blick", russian: "Взгляд, вид" },
        { german: "Blume", russian: "Цветок" },
        { german: "Boden", russian: "Пол; земля, почва" },
        { german: "Bohne", russian: "Фасоль, боб" },
        { german: "Brief", russian: "Письмо" },
        { german: "Briefmarke", russian: "Почтовая марка" },
        { german: "Brot", russian: "Хлеб" }, // Brot - было в А0, здесь может быть как повторение
        { german: "Bruder", russian: "Брат" },
        { german: "Buchstabe", russian: "Буква" },
        { german: "Bürgermeister", russian: "Мэр, бургомистр" },
        { german: "Café", russian: "Кафе" },
        { german: "Chance", russian: "Шанс, возможность" },
        { german: "Dach", russian: "Крыша" },
        { german: "Datum", russian: "Дата" },
        { german: "Deutsch", russian: "Немецкий язык" }, // das Deutsch
        { german: "Dezember", russian: "Декабрь" },
        { german: "Disko", russian: "Дискотека" },
        { german: "Dusche", russian: "Душ" },
        { german: "Ei", russian: "Яйцо" },
        { german: "Einkauf", russian: "Покупка, закупка" },
        { german: "Elefant", russian: "Слон" },
        { german: "Erdbeere", russian: "Клубника" },
        { german: "Etage", russian: "Этаж" },
        { german: "Euro", russian: "Евро (валюта)" },
        { german: "Fahrstuhl", russian: "Лифт" },
        { german: "Familie", russian: "Семья" },
        { german: "Februar", russian: "Февраль" },
        { german: "Fernseher", russian: "Телевизор" },
        { german: "Firma", russian: "Фирма, компания" },
        { german: "Flughafen", russian: "Аэропорт" },
        { german: "Flugzeug", russian: "Самолёт" },
        { german: "Frage", russian: "Вопрос" },
        { german: "Freitag", russian: "Пятница" },
        { german: "Freund", russian: "Друг" }, // Freundin - подруга
        { german: "Freundin", russian: "Подруга" },
        { german: "Fahrrad", russian: "Велосипед" },
        { german: "Fuß", russian: "Нога, стопа" },
        { german: "Garten", russian: "Сад" },
        { german: "Geld", russian: "Деньги" },
        { german: "Geschenk", russian: "Подарок" },
        { german: "Geschirr", russian: "Посуда" },
        { german: "Gesicht", russian: "Лицо" },
        { german: "Gespräch", russian: "Разговор, беседа" },
        { german: "Getränk", russian: "Напиток" },
        { german: "Gewicht", russian: "Вес" },
        { german: "Glocke", russian: "Колокол, звонок" },
        { german: "Gott", russian: "Бог" },
        { german: "Geburtstag", russian: "День рождения" },
        { german: "Hafen", russian: "Порт, гавань" },
        { german: "Halle", russian: "Зал, холл" },
        { german: "Hotel", russian: "Отель, гостиница" },
        { german: "Hund", russian: "Собака" },
        { german: "Idee", russian: "Идея, мысль" },
        { german: "Januar", russian: "Январь" },
        { german: "Jugendliche", russian: "Подросток, молодежь" }, // Der/Die Jugendliche
        { german: "Kaffee", russian: "Кофе" },
        { german: "Kamera", russian: "Камера, фотоаппарат" },
        { german: "Kasten", russian: "Ящик, коробка" },
        { german: "Kindergarten", russian: "Детский сад" },
        { german: "König", russian: "Король" },
        { german: "Küche", russian: "Кухня" },
        { german: "Lehrer", russian: "Учитель" },
        { german: "Löffel", russian: "Ложка" },
        { german: "Montag", russian: "Понедельник" },
        { german: "Opa", russian: "Дедушка" },
        { german: "Oma", russian: "Бабушка" },
        { german: "Onkel", russian: "Дядя" },
        { german: "Ort", russian: "Место; населённый пункт" },
        { german: "Park", russian: "Парк" },
        { german: "Passwort", russian: "Пароль" },
        { german: "Rad", russian: "Колесо; велосипед (сокр.)" },
        { german: "Regen", russian: "Дождь" },
        { german: "Restaurant", russian: "Ресторан" },
        { german: "Saft", russian: "Сок" },
        { german: "Schlaf", russian: "Сон" }, // от schlafen
        { german: "Schule", russian: "Школа" },
        { german: "Sonntag", russian: "Воскресенье" },
        { german: "Stück", russian: "Кусок, штука; пьеса" },
        { german: "Test", russian: "Тест, проверка" },
        { german: "Tür", russian: "Дверь" }, // было в А0
        { german: "Uhr", russian: "Часы; час (время)" }, // было в А0
        { german: "Woche", russian: "Неделя" }, // было в А0
        { german: "Zuhause", russian: "Дом (как родное место), домашний очаг" }, // das Zuhause
      ]
    },
    {
      id: "a1_numbers_extended",
      name: "Числительные и счет (A1)",
      fallbackVocabulary: [
        { german: "acht", russian: "Восемь" },
        { german: "achtzig", russian: "Восемьдесят" },
        { german: "elf", russian: "Одиннадцать" },
        { german: "eins", russian: "Один" }, // Повторение А0
        { german: "neun", russian: "Девять" }, // Повторение А0
      ]
    },
  ],
  A2: [
    {
      id: "a2_daily_life_routine_planning", name: "Повседневная жизнь",
      fallbackVocabulary: [
        { german: "Abendessen", russian: "Ужин" },
        { german: "Adresse", russian: "Адрес" },
        { german: "Ausflug", russian: "Экскурсия, поездка" },
        { german: "Besuch", russian: "Посещение, визит; гости" },
        { german: "Datum", russian: "Дата" },
        { german: "Einwohner", russian: "Житель" },
        { german: "Erlebnis", russian: "Переживание, событие" },
        { german: "Familienmitglied", russian: "Член семьи" },
        { german: "Feier", russian: "Праздник, торжество" },
        { german: "Fernsehen", russian: "Телевидение" },
        { german: "Fest", russian: "Праздник" },
        { german: "Flasche", russian: "Бутылка" },
        { german: "Freizeit", russian: "Свободное время, досуг" },
        { german: "Frühstück", russian: "Завтрак" },
        { german: "Gemüse", russian: "Овощи" },
        { german: "Gericht", russian: "Блюдо (еда); суд" },
        { german: "Geschenk", russian: "Подарок" },
        { german: "Handy", russian: "Мобильный телефон" },
        { german: "Hochzeit", russian: "Свадьба" },
        { german: "Jahr", russian: "Год" },
        { german: "Jugendliche", russian: "Подросток, молодежь" },
        { german: "Kinderzimmer", russian: "Детская комната" },
        { german: "Kino", russian: "Кино, кинотеатр" },
        { german: "Kissen", russian: "Подушка" },
        { german: "Küche", russian: "Кухня" },
        { german: "Kunst", russian: "Искусство" },
        { german: "Lampe", russian: "Лампа" },
        { german: "Lied", russian: "Песня" },
        { german: "Messer", russian: "Нож" },
        { german: "Miete", russian: "Арендная плата" },
        { german: "Mittag", russian: "Полдень, обед" },
        { german: "Moment", russian: "Момент, мгновение" },
        { german: "Mutter", russian: "Мать" },
        { german: "Nachbar", russian: "Сосед" },
        { german: "Obst", russian: "Фрукты" },
        { german: "Pause", russian: "Перерыв, пауза" },
        { german: "Programm", russian: "Программа" },
        { german: "Radio", russian: "Радио" },
        { german: "Restaurant", russian: "Ресторан" },
        { german: "Schrank", russian: "Шкаф" },
        { german: "Sekunde", russian: "Секунда" },
        { german: "Spiel", russian: "Игра" },
        { german: "Sport", russian: "Спорт" },
        { german: "Stock", russian: "Этаж; палка" },
        { german: "Stunde", russian: "Час" },
        { german: "Stuhl", russian: "Стул" },
        { german: "Tag", russian: "День" },
        { german: "Telefon", russian: "Телефон" },
        { german: "Theater", russian: "Театр" },
        { german: "Trinken", russian: "Напиток; питьё" }, // das Trinken
        { german: "Tür", russian: "Дверь" },
        { german: "Uhr", russian: "Часы; час (время)" },
        { german: "Vater", russian: "Отец" },
        { german: "Wand", russian: "Стена" },
        { german: "Wasser", russian: "Вода" },
        { german: "Wein", russian: "Вино" },
        { german: "Woche", russian: "Неделя" },
        { german: "Wohnung", russian: "Квартира" },
        { german: "Zeit", russian: "Время" },
        { german: "Zimmer", russian: "Комната" },
        { german: "Zucker", russian: "Сахар" },
      ]
    },
    {
      id: "a2_work_professions_environment", name: "Работа и профессии",
      fallbackVocabulary: [
        { german: "Arbeit", russian: "Работа" },
        { german: "Arbeitsplatz", russian: "Рабочее место" },
        { german: "Aufgabe", russian: "Задача, задание" },
        { german: "Dienst", russian: "Служба, дежурство" },
        { german: "Einstellung", russian: "Прием на работу; настройка; отношение" },
        { german: "Erfolg", russian: "Успех" },
        { german: "Erfahrung", russian: "Опыт" },
        { german: "Koch", russian: "Повар" },
        { german: "Kunde", russian: "Клиент, покупатель" },
        { german: "Lehrer", russian: "Учитель" },
        { german: "Leistung", russian: "Достижение, производительность" },
        { german: "Maler", russian: "Художник; маляр" },
        { german: "Stelle", russian: "Место; должность" },
        { german: "Unterricht", russian: "Урок, занятие, обучение" },
        { german: "Verlag", russian: "Издательство" },
        { german: "Werkzeug", russian: "Инструмент" },
      ]
    },
    {
      id: "a2_travel_holidays_experiences", name: "Путешествия и отдых",
      fallbackVocabulary: [
        { german: "Auto", russian: "Автомобиль" },
        { german: "Bahn", russian: "Железная дорога, поезд" },
        { german: "Boot", russian: "Лодка, судно" },
        { german: "Fahrkarte", russian: "Билет (на транспорт)" },
        { german: "Ferien", russian: "Каникулы, отпуск" },
        { german: "Flugzeug", russian: "Самолёт" },
        { german: "Führung", russian: "Экскурсия; руководство" },
        { german: "Hauptstadt", russian: "Столица" },
        { german: "Hof", russian: "Двор; ферма" },
        { german: "Hotel", russian: "Отель, гостиница" },
        { german: "Karte", russian: "Карта; билет; открытка" },
        { german: "Koffer", russian: "Чемодан" },
        { german: "Reise", russian: "Путешествие, поездка" },
        { german: "Roller", russian: "Самокат; скутер" },
        { german: "Rucksack", russian: "Рюкзак" },
        { german: "Urlaub", russian: "Отпуск" },
        { german: "Verkehr", russian: "Движение, транспорт" },
        { german: "Zug", russian: "Поезд" },
      ]
    },
    {
      id: "a2_shopping_services_complaints", name: "Покупки и магазины",
      fallbackVocabulary: [
        { german: "Geschäft", russian: "Магазин; дело" },
        { german: "Geldautomat", russian: "Банкомат" },
        { german: "Kleidung", russian: "Одежда" },
        { german: "Kosten", russian: "Расходы, стоимость" },
        { german: "Kreditkarte", russian: "Кредитная карта" },
        { german: "Markt", russian: "Рынок" },
        { german: "Post", russian: "Почта" },
        { german: "Preis", russian: "Цена" },
        { german: "Rock", russian: "Юбка" }, // Мужской артикль der Rock
        { german: "Tasche", russian: "Сумка; карман" },
        { german: "Versicherung", russian: "Страховка, страхование" },
      ]
    },
    {
      id: "a2_health_body_appointments", name: "Здоровье",
      fallbackVocabulary: [
        { german: "Apotheke", russian: "Аптека" },
        { german: "Körper", russian: "Тело" },
        { german: "Krankenhaus", russian: "Больница" },
        { german: "Mund", russian: "Рот" },
        { german: "Schmerz", russian: "Боль" },
        { german: "Schulter", russian: "Плечо" },
        { german: "Unfall", russian: "Несчастный случай, авария" },
        { german: "Verletzung", russian: "Травма, ранение" },
      ]
    },
    {
      id: "a2_character_emotions_expression", name: "Характер и эмоции",
      fallbackVocabulary: [
        { german: "Angst", russian: "Страх" },
        { german: "Ehre", russian: "Честь, почёт" },
        { german: "Glück", russian: "Счастье, удача" },
        { german: "Lachen", russian: "Смех" }, // das Lachen
        { german: "Liebe", russian: "Любовь" },
        { german: "Traum", russian: "Сон, мечта" },
      ]
    },
    {
      id: "a2_nature_environment_protection_basic", name: "Природа и окружающая среда",
      fallbackVocabulary: [
        { german: "Berg", russian: "Гора" },
        { german: "Blatt", russian: "Лист (дерева, бумаги)" },
        { german: "Feld", russian: "Поле" },
        { german: "Katze", russian: "Кошка" },
        { german: "Land", russian: "Страна; сельская местность; земля" },
        { german: "Natur", russian: "Природа" },
        { german: "Nebel", russian: "Туман" },
        { german: "Park", russian: "Парк" },
        { german: "Pferd", russian: "Лошадь" },
        { german: "Pflanze", russian: "Растение" },
        { german: "Regen", russian: "Дождь" },
        { german: "Saison", russian: "Сезон" },
        { german: "Schaf", russian: "Овца" },
        { german: "See", russian: "Озеро (der See); море (die See)" },
        { german: "Sonne", russian: "Солнце" },
        { german: "Tier", russian: "Животное" },
        { german: "Umgebung", russian: "Окрестности, окружение" },
        { german: "Vogel", russian: "Птица" },
        { german: "Wald", russian: "Лес" },
        { german: "Wetter", russian: "Погода" },
      ]
    },
    {
      id: "a2_general_nouns", name: "Общие существительные (A2)",
      fallbackVocabulary: [
        { german: "Anfang", russian: "Начало" },
        { german: "Antwort", russian: "Ответ" },
        { german: "Aufzug", russian: "Лифт" },
        { german: "Ausgang", russian: "Выход" },
        { german: "Ausländer", russian: "Иностранец" },
        { german: "Baustelle", russian: "Стройка" },
        { german: "Bedingung", russian: "Условие" },
        { german: "Beispiel", russian: "Пример" },
        { german: "Bild", russian: "Картина, изображение" },
        { german: "Blick", russian: "Взгляд, вид" },
        { german: "Buchstabe", russian: "Буква" },
        { german: "Dame", russian: "Дама, госпожа" },
        { german: "Dank", russian: "Благодарность" }, // der Dank
        { german: "Decke", russian: "Потолок; одеяло" },
        { german: "Diskussion", russian: "Дискуссия, обсуждение" },
        { german: "Durchschnitt", russian: "Среднее значение, в среднем" },
        { german: "Ebene", russian: "Уровень, плоскость; равнина" },
        { german: "Eingang", russian: "Вход" },
        { german: "Ende", russian: "Конец" },
        { german: "Entscheidung", russian: "Решение" },
        { german: "Erlaubnis", russian: "Разрешение" },
        { german: "Fehler", russian: "Ошибка" },
        { german: "Frage", russian: "Вопрос" },
        { german: "Gefahr", russian: "Опасность" },
        { german: "Geheimnis", russian: "Тайна, секрет" },
        { german: "Gebäude", russian: "Здание, строение" },
        { german: "Gegenstand", russian: "Предмет, вещь" },
        { german: "Geschwindigkeit", russian: "Скорость" },
        { german: "Gespräch", russian: "Разговор, беседа" },
        { german: "Gold", russian: "Золото" },
        { german: "Gruppe", russian: "Группа" },
        { german: "Grund", russian: "Причина, основание; земля" },
        { german: "Hilfe", russian: "Помощь" },
        { german: "Idee", russian: "Идея" },
        { german: "Information", russian: "Информация" },
        { german: "Kampf", russian: "Борьба, бой" },
        { german: "Keller", russian: "Подвал" },
        { german: "Kirche", russian: "Церковь" },
        { german: "Klasse", russian: "Класс" },
        { german: "Knopf", russian: "Кнопка; пуговица" },
        { german: "Kommune", russian: "Коммуна, муниципалитет" },
        { german: "Krieg", russian: "Война" }, // Специфично, но может встретиться
        { german: "Leben", russian: "Жизнь" }, // das Leben
        { german: "Licht", russian: "Свет" },
        { german: "Lösung", russian: "Решение (проблемы)" },
        { german: "Mädchen", russian: "Девочка" },
        { german: "Maschine", russian: "Машина, механизм" },
        { german: "Meter", russian: "Метр" },
        { german: "Mitglied", russian: "Член (организации)" },
        { german: "Nachricht", russian: "Новость, сообщение" },
        { german: "Niveau", russian: "Уровень" },
        { german: "Ort", russian: "Место" }, // был в A1, повтор для контекста
        { german: "Paar", russian: "Пара" },
        { german: "Pflanze", russian: "Растение" }, // был в природе, но может быть и общим
        { german: "Polizei", russian: "Полиция" },
        { german: "Problem", russian: "Проблема" },
        { german: "Prüfung", russian: "Экзамен, проверка" },
        { german: "Qualität", russian: "Качество" },
        { german: "Rhythmus", russian: "Ритм" },
        { german: "Richtung", russian: "Направление" },
        { german: "Sache", russian: "Вещь, дело" },
        { german: "Schlüssel", russian: "Ключ" },
        { german: "Schule", russian: "Школа" }, // был в A0, повтор
        { german: "Seite", russian: "Страница; сторона" },
        { german: "Stadt", russian: "Город" }, // был в A0, повтор
        { german: "Straße", russian: "Улица" }, // был в A0, повтор
        { german: "Tor", russian: "Ворота; гол" },
        { german: "Treppe", russian: "Лестница" },
        { german: "Weg", russian: "Путь, дорога" }, // был в A0, повтор
        { german: "Wort", russian: "Слово" },
        { german: "Zahl", russian: "Число, цифра" },
      ]
    }
  ],
  B1: [
    { id: "b1_education_studies_systems", name: "Образование и учёба", fallbackVocabulary: [] },
    { id: "b1_professions_career_planning_application", name: "Профессии и карьера", fallbackVocabulary: [] },
    { id: "b1_society_interpersonal_relations_issues", name: "Общество и межличностные отношения", fallbackVocabulary: [] },
    { id: "b1_media_technology_internet_impact", name: "Медиа и технологии", fallbackVocabulary: [] },
    { id: "b1_ecology_health_lifestyle_choices", name: "Экология и здоровье", fallbackVocabulary: [] },
    { id: "b1_travel_intercultural_communication_experiences", name: "Путешествия и межкультурная коммуникация", fallbackVocabulary: [] },
    { id: "b1_events_incidents_reporting", name: "События и происшествия", fallbackVocabulary: [] }
  ],
  B2: [
    { id: "b2_politics_economics_global_systems", name: "Политика и экономика", fallbackVocabulary: [] },
    { id: "b2_science_technology_innovations_discussion", name: "Наука и техника", fallbackVocabulary: [] },
    { id: "b2_culture_art_literature_analysis", name: "Культура и искусство", fallbackVocabulary: [] },
    { id: "b2_work_career_advanced_strategies", name: "Работа и карьера", fallbackVocabulary: [] },
    { id: "b2_social_issues_discussion_solutions", name: "Социальные проблемы", fallbackVocabulary: [] }
  ],
  C1: [
    { id: "c1_philosophy_psychology_ethics_concepts", name: "Философия и психология", fallbackVocabulary: [] },
    { id: "c1_political_debates_globalization_analysis", name: "Политические дебаты", fallbackVocabulary: [] },
    { id: "c1_science_global_challenges_ai_implications", name: "Наука и глобальные вызовы", fallbackVocabulary: [] },
    { id: "c1_academic_professional_lexis_discourse", name: "Академическая и профессиональная лексика", fallbackVocabulary: [] }
  ],
  C2: [
    { id: "c2_literary_publicistic_language_nuances", name: "Литературный и публицистический язык", fallbackVocabulary: [] },
    { id: "c2_legal_scientific_style_application", name: "Юридический и научный стиль", fallbackVocabulary: [] },
    { id: "c2_formal_informal_registers_diplomacy_discourse", name: "Формальный и неформальный регистры", fallbackVocabulary: [] },
    { id: "c2_translation_interpretation_cultural_nuances_practice", name: "Перевод и интерпретация", fallbackVocabulary: [] }
  ],
};

// Mandatory Grammar Topics per Level
export const MANDATORY_GRAMMAR_TOPICS: Record<LanguageLevel, string[]> = {
    A0: [
      "Алфавит и фонетика (произношение букв, ударения)",
      "Личные местоимения (ich, du, er, sie, es, wir, ihr, sie, Sie)",
      "Глагол sein в настоящем времени (ich bin, du bist…)",
      "Глагол haben в настоящем времени",
      "Простое повествовательное предложение (SVO)",
      "Простое вопросительное предложение (Ja/Nein-Fragen)",
      "Числа (0–100)",
      "Простые артикли (der, die, das – определённые)",
      "Простая лексика: дни недели, цвета, семья, еда, время"
    ],
    A1: [
      "Существительные и артикли (определённый / неопределённый)",
      "Множественное число существительных",
      "Притяжательные местоимения (mein, dein, sein…)",
      "Указательные местоимения (dieser, diese, dieses)",
      "Вопросительные слова (wer, was, wo, wann, wie, warum…)",
      "Настоящее время (Präsens) слабых и сильных глаголов",
      "Модальные глаголы (können, müssen, wollen, dürfen, sollen, mögen)",
      "Глаголы с отделяемыми приставками (aufstehen, anrufen…)",
      "Порядок слов в утвердительных, вопросительных и отрицательных предложениях",
      "Инверсия (сначала обстоятельство, потом подлежащее)",
      "Отрицание с nicht и kein",
      "Imperativ (повелительное наклонение) — вежливый и неформальный",
      "Время в часах (Uhrzeit)",
      "Именительный (Nominativ)",
      "Винительный (Akkusativ) (Ich sehe den Mann.)",
      "Простые предлоги с Akkusativ (für, durch, ohne, um…)"
    ],
    A2: [
      "Притяжательные местоимения во всех падежах",
      "Вопросительные местоимения в других падежах (Wem? Wen?)",
      "Относительные местоимения (Relativsätze mit der/die/das)",
      "Наречия частотности и времени (oft, selten, manchmal…)",
      "Наречия порядка и места (zuerst, dann, dort…)",
      "Прошедшее время: Perfekt (Ich habe gegessen, Ich bin gegangen…)",
      "Слово порядок при использовании Perfekt",
      "Präteritum некоторых глаголов (sein, haben, modal verbs)",
      "Начало освоения пассивного залога в Perfekt (wird… gemacht)",
      "Дательный падеж (Dativ)",
      "Предлоги с Dativ (mit, nach, seit, bei, von, zu…)",
      "Предлоги с Akkusativ und Dativ (an, auf, in, über…)",
      "Временные конструкции (seit, vor, in, bis)"
    ],
    B1: [
      "Относительные предложения с разными падежами",
      "Условные предложения типа I (Wenn-Sätze Typ 1)",
      "Конъюнкции: weil, obwohl, wenn, dass, damit, während",
      "Союзы и порядок слов",
      "Причастия I и II в качестве прилагательных",
      "Präteritum регулярно и часто употребляемых глаголов",
      "Различие между Präteritum и Perfekt",
      "Пассивный залог в Präsens, Präteritum и Perfekt",
      "Futur I (ich werde arbeiten)",
      "Начало Futur II (ich werde gearbeitet haben)",
      "Специальные конструкции: Es gibt / es gab",
      "Indirekte Rede mit Konjunktiv I (начало)",
      "Verben mit Präpositionen (sich freuen auf/über, warten auf)"
    ],
    B2: [
      "Konjunktiv I в косвенной речи",
      "Konjunktiv II: нереальные условные предложения (würde + Infinitiv)",
      "Konjunktiv II с Präteritum сильных глаголов (hätte, wäre, könnte, müsste)",
      "Futur II",
      "Страдательный залог (Passiv) во всех временах, в том числе с модальными глаголами",
      "Zustandspassiv (sein + Partizip II)",
      "Vorgangspassiv (werden + Partizip II)",
      "Условные предложения всех типов (Typ 1–3)",
      "Употребление инфинитивных конструкций с zu",
      "Номинализация (der Besuch → besuchen, das Lesen → lesen)",
      "Префиксы и суффиксы образования слов",
      "Сложносочинённые и сложноподчинённые предложения с Nebensätzen",
      "Рекурсия придаточных предложений"
    ],
    C1: [
      "Продвинутое использование Konjunktiv I и II",
      "Высокая частота Passiv и Umschreibungen",
      "Различия в значении при смене порядка слов",
      "Stilistische Unterschiede: Umgangssprache vs. Schriftsprache",
      "Erweiterter Infinitiv mit zu (um zu…, ohne zu…, anstatt zu…)",
      "Partizipialkonstruktionen (z.B. Von der Polizei verfolgt, rannte er weg…)",
      "Сложные причастные обороты",
      "Nominalstil vs. Verbalstil (научный стиль)",
      "Разнообразные способы выражения причины, цели, следствия"
    ],
    C2: [
      "Метафорические и идиоматические обороты",
      "Структуры высокого уровня сложности:",
      "Инверсия ради акцента: Kaum hatte er das Haus verlassen, da…",
      "Eliptische формы (пропуски глаголов/подлежащих)",
      "Dialektные и региональные формы (опционально)",
      "Структуры со сложными глаголами и вводными конструкциями",
      "Стилистические оттенки Konjunktiv I в официальных документах",
      "Академическая лексика и синтаксис",
      "Юридические и научные формулировки",
      "Перевод и переформулировка сложных идей",
      "Все времена и залоги, включая сложные и редкие формы (например, Zustandspassiv)",
      "Все формы и случаи употребления Konjunktiv I и II, включая Ersatzformen",
      "Сложные синтаксические конструкции, периоды",
      "Употребление модальных частиц для выражения оттенков значения (doch, ja, eben, halt, wohl и т.д.)",
      "Стилистически окрашенная лексика и грамматика",
      "Особенности научного и делового стиля",
      "Фразеология и идиоматика на продвинутом уровне",
      "Различия между письменной и устной речью на высоком уровне",
      "Тонкости словообразования (суффиксы, префиксы, сложные слова)",
      "Сложные случаи предложного управления и рекций глаголов"
    ],
};
